/**
 * Camera Movement Presets for FilmFlow AI
 * Professional cinematic camera movements for video generation
 */

export const cameraMovements = [
  // ==========================================
  // BASIC MOVEMENTS
  // ==========================================
  {
    category: 'basic',
    name: 'Static',
    nameSk: 'Statický záber',
    description: 'Locked-off shot, no movement',
    descriptionSk: 'Nehybná kamera, žiadny pohyb',
    prompt: 'static shot, locked camera, no movement, stable tripod shot',
    dramaticUse: 'Dialogue scenes, building tension, allowing viewer to focus',
    emotionalEffect: 'Stability, focus, sometimes unease',
    videoPrompt: 'camera: static',
  },
  {
    category: 'basic',
    name: 'Pan Left',
    nameSk: 'Panoráma vľavo',
    description: 'Camera rotates horizontally to the left',
    descriptionSk: 'Kamera sa otáča horizontálne doľava',
    prompt: 'smooth pan left, horizontal camera rotation, following action',
    dramaticUse: 'Revealing environment, following character, showing reaction',
    emotionalEffect: 'Discovery, connection between elements',
    videoPrompt: 'camera: pan left',
  },
  {
    category: 'basic',
    name: 'Pan Right',
    nameSk: 'Panoráma vpravo',
    description: 'Camera rotates horizontally to the right',
    descriptionSk: 'Kamera sa otáča horizontálne doprava',
    prompt: 'smooth pan right, horizontal camera rotation, revealing scene',
    dramaticUse: 'Revealing environment, following character movement',
    emotionalEffect: 'Discovery, anticipation',
    videoPrompt: 'camera: pan right',
  },
  {
    category: 'basic',
    name: 'Tilt Up',
    nameSk: 'Naklonenie hore',
    description: 'Camera tilts upward vertically',
    descriptionSk: 'Kamera sa nakláňa vertikálne nahor',
    prompt: 'slow tilt up, vertical camera movement upward, revealing height',
    dramaticUse: 'Revealing tall subjects, showing power, hope',
    emotionalEffect: 'Aspiration, power, revelation',
    videoPrompt: 'camera: tilt up',
  },
  {
    category: 'basic',
    name: 'Tilt Down',
    nameSk: 'Naklonenie dole',
    description: 'Camera tilts downward vertically',
    descriptionSk: 'Kamera sa nakláňa vertikálne nadol',
    prompt: 'slow tilt down, vertical camera movement downward, descending view',
    dramaticUse: 'Revealing ground-level details, showing descent, loss',
    emotionalEffect: 'Discovery, descent, melancholy',
    videoPrompt: 'camera: tilt down',
  },

  // ==========================================
  // DOLLY MOVEMENTS
  // ==========================================
  {
    category: 'dolly',
    name: 'Dolly In',
    nameSk: 'Jazda dopredu',
    description: 'Camera moves forward toward subject',
    descriptionSk: 'Kamera sa pohybuje smerom k subjektu',
    prompt: 'smooth dolly in, camera pushing toward subject, increasing intimacy',
    dramaticUse: 'Building emotional connection, emphasizing importance',
    emotionalEffect: 'Intimacy, intensity, focus',
    videoPrompt: 'camera: dolly in, push in',
  },
  {
    category: 'dolly',
    name: 'Dolly Out',
    nameSk: 'Jazda dozadu',
    description: 'Camera moves backward away from subject',
    descriptionSk: 'Kamera sa vzďaľuje od subjektu',
    prompt: 'smooth dolly out, camera pulling back from subject, revealing context',
    dramaticUse: 'Revealing environment, creating distance, isolation',
    emotionalEffect: 'Revelation, isolation, perspective',
    videoPrompt: 'camera: dolly out, pull back',
  },
  {
    category: 'dolly',
    name: 'Dolly Zoom (Vertigo)',
    nameSk: 'Vertigo efekt',
    description: 'Dolly and zoom simultaneously in opposite directions',
    descriptionSk: 'Súčasná jazda a zoom v opačných smeroch',
    prompt: 'dolly zoom, vertigo effect, background warping while subject stays same size',
    dramaticUse: 'Disorientation, realization, emotional shift',
    emotionalEffect: 'Unease, revelation, psychological shift',
    videoPrompt: 'camera: vertigo effect, dolly zoom',
  },

  // ==========================================
  // TRACKING SHOTS
  // ==========================================
  {
    category: 'tracking',
    name: 'Track Left',
    nameSk: 'Jazda vľavo',
    description: 'Camera moves laterally to the left',
    descriptionSk: 'Kamera sa pohybuje bočne doľava',
    prompt: 'smooth tracking shot left, lateral camera movement, parallel to subject',
    dramaticUse: 'Following action, revealing scene, creating rhythm',
    emotionalEffect: 'Movement, energy, discovery',
    videoPrompt: 'camera: track left, lateral movement',
  },
  {
    category: 'tracking',
    name: 'Track Right',
    nameSk: 'Jazda vpravo',
    description: 'Camera moves laterally to the right',
    descriptionSk: 'Kamera sa pohybuje bočne doprava',
    prompt: 'smooth tracking shot right, lateral camera movement, sliding',
    dramaticUse: 'Following action, scene transition, visual flow',
    emotionalEffect: 'Movement, continuity, progression',
    videoPrompt: 'camera: track right, lateral movement',
  },
  {
    category: 'tracking',
    name: 'Following Shot',
    nameSk: 'Sledovací záber',
    description: 'Camera follows subject from behind',
    descriptionSk: 'Kamera sleduje subjekt zozadu',
    prompt: 'following shot, camera behind subject, tracking movement, walking or running',
    dramaticUse: 'Journey sequences, building anticipation, character POV',
    emotionalEffect: 'Engagement, journey, anticipation',
    videoPrompt: 'camera: following shot, behind subject',
  },
  {
    category: 'tracking',
    name: 'Lead Shot',
    nameSk: 'Vedúci záber',
    description: 'Camera moves ahead of subject, facing them',
    descriptionSk: 'Kamera ide pred subjektom a sníma ho spredu',
    prompt: 'lead shot, camera moving backward facing subject, subject walks toward camera',
    dramaticUse: 'Character focus, determination, confrontation',
    emotionalEffect: 'Connection, intention, determination',
    videoPrompt: 'camera: lead shot, facing subject',
  },

  // ==========================================
  // CRANE/JIB MOVEMENTS
  // ==========================================
  {
    category: 'crane',
    name: 'Crane Up',
    nameSk: 'Žeriav hore',
    description: 'Camera rises vertically on crane',
    descriptionSk: 'Kamera sa vertikálne zdvíha na žeriave',
    prompt: 'crane shot rising up, vertical elevation, revealing wider scene',
    dramaticUse: 'Ending scenes, revelation, transcendence',
    emotionalEffect: 'Liberation, transcendence, finality',
    videoPrompt: 'camera: crane up, rising shot',
  },
  {
    category: 'crane',
    name: 'Crane Down',
    nameSk: 'Žeriav dole',
    description: 'Camera descends vertically on crane',
    descriptionSk: 'Kamera sa vertikálne spúšťa na žeriave',
    prompt: 'crane shot descending, camera lowering from height, revealing subject',
    dramaticUse: 'Introduction of character, establishing scene',
    emotionalEffect: 'Arrival, introduction, grounding',
    videoPrompt: 'camera: crane down, descending shot',
  },
  {
    category: 'crane',
    name: 'Boom Up',
    nameSk: 'Výťah',
    description: 'Camera lifts straight up while maintaining framing',
    descriptionSk: 'Kamera sa zdvíha priamo hore so zachovaním kompozície',
    prompt: 'boom up shot, camera elevating vertically, subject remains in frame',
    dramaticUse: 'Emotional climax, character growth, revelation',
    emotionalEffect: 'Elevation, triumph, realization',
    videoPrompt: 'camera: boom up',
  },

  // ==========================================
  // ORBIT/ARC MOVEMENTS
  // ==========================================
  {
    category: 'orbit',
    name: 'Arc Left',
    nameSk: 'Oblúk vľavo',
    description: 'Camera arcs around subject to the left',
    descriptionSk: 'Kamera obieha okolo subjektu doľava',
    prompt: 'arc shot left, camera orbiting subject counter-clockwise, circling movement',
    dramaticUse: 'Hero shots, romantic moments, dramatic reveals',
    emotionalEffect: 'Importance, romance, drama',
    videoPrompt: 'camera: arc left, orbit counter-clockwise',
  },
  {
    category: 'orbit',
    name: 'Arc Right',
    nameSk: 'Oblúk vpravo',
    description: 'Camera arcs around subject to the right',
    descriptionSk: 'Kamera obieha okolo subjektu doprava',
    prompt: 'arc shot right, camera orbiting subject clockwise, circular movement',
    dramaticUse: 'Revealing scene, character focus, tension',
    emotionalEffect: 'Engagement, revelation, intensity',
    videoPrompt: 'camera: arc right, orbit clockwise',
  },
  {
    category: 'orbit',
    name: '360 Orbit',
    nameSk: '360° otočka',
    description: 'Camera completes full circle around subject',
    descriptionSk: 'Kamera obíde okolo subjektu celý kruh',
    prompt: 'full 360 orbit shot, camera circling completely around subject, dramatic',
    dramaticUse: 'Major emotional moments, climactic scenes',
    emotionalEffect: 'Intensity, isolation, importance',
    videoPrompt: 'camera: 360 orbit, full circle',
  },

  // ==========================================
  // ZOOM MOVEMENTS
  // ==========================================
  {
    category: 'zoom',
    name: 'Slow Zoom In',
    nameSk: 'Pomalý zoom',
    description: 'Gradual zoom toward subject',
    descriptionSk: 'Postupný zoom smerom k subjektu',
    prompt: 'slow zoom in, gradual lens zoom toward subject, building intensity',
    dramaticUse: 'Building tension, emphasizing emotion, focus',
    emotionalEffect: 'Tension, intimacy, importance',
    videoPrompt: 'camera: slow zoom in',
  },
  {
    category: 'zoom',
    name: 'Crash Zoom',
    nameSk: 'Rýchly zoom',
    description: 'Fast dramatic zoom to subject',
    descriptionSk: 'Rýchly dramatický zoom k subjektu',
    prompt: 'crash zoom, fast dramatic zoom toward subject, sudden intensity',
    dramaticUse: 'Shock moments, reactions, emphasis',
    emotionalEffect: 'Shock, emphasis, intensity',
    videoPrompt: 'camera: crash zoom, fast zoom in',
  },

  // ==========================================
  // HANDHELD/SPECIAL
  // ==========================================
  {
    category: 'handheld',
    name: 'Handheld Natural',
    nameSk: 'Z ruky - prirodzený',
    description: 'Subtle handheld movement for documentary feel',
    descriptionSk: 'Jemný pohyb z ruky pre dokumentárny efekt',
    prompt: 'handheld shot, natural subtle movement, documentary style, organic feel',
    dramaticUse: 'Intimate scenes, realism, tension',
    emotionalEffect: 'Realism, intimacy, urgency',
    videoPrompt: 'camera: handheld, slight movement',
  },
  {
    category: 'handheld',
    name: 'Shaky Intense',
    nameSk: 'Z ruky - intenzívny',
    description: 'Intentionally unstable for tension',
    descriptionSk: 'Zámerne nestabilný pre napätie',
    prompt: 'shaky handheld, unstable camera, chaotic movement, intense',
    dramaticUse: 'Action scenes, panic, chaos',
    emotionalEffect: 'Chaos, urgency, unease',
    videoPrompt: 'camera: shaky handheld, intense movement',
  },
  {
    category: 'special',
    name: 'Dutch Angle',
    nameSk: 'Holandský uhol',
    description: 'Camera tilted on its axis',
    descriptionSk: 'Kamera naklonená na osi',
    prompt: 'dutch angle, tilted camera, skewed horizon, disorienting',
    dramaticUse: 'Unease, madness, tension, disorientation',
    emotionalEffect: 'Unease, tension, psychological',
    videoPrompt: 'camera: dutch angle, tilted',
  },
  {
    category: 'special',
    name: 'Low Angle Power',
    nameSk: 'Podhľad - sila',
    description: 'Camera looking up at subject',
    descriptionSk: 'Kamera sa pozerá na subjekt zdola',
    prompt: 'low angle shot, camera below subject looking up, empowering, heroic',
    dramaticUse: 'Hero moments, power, dominance',
    emotionalEffect: 'Power, heroism, intimidation',
    videoPrompt: 'camera: low angle, looking up',
  },
  {
    category: 'special',
    name: 'High Angle Vulnerable',
    nameSk: 'Nadhľad - zraniteľnosť',
    description: 'Camera looking down at subject',
    descriptionSk: 'Kamera sa pozerá na subjekt zhora',
    prompt: 'high angle shot, camera above subject looking down, vulnerable, small',
    dramaticUse: 'Vulnerability, insignificance, observation',
    emotionalEffect: 'Vulnerability, powerlessness, observation',
    videoPrompt: 'camera: high angle, looking down',
  },
  {
    category: 'special',
    name: 'Bird\'s Eye',
    nameSk: 'Vtáčia perspektíva',
    description: 'Directly overhead shot',
    descriptionSk: 'Záber priamo zhora',
    prompt: 'birds eye view, camera directly overhead, top down perspective, god view',
    dramaticUse: 'Establishing, artistic, pattern reveal',
    emotionalEffect: 'Detachment, perspective, artistic',
    videoPrompt: 'camera: birds eye view, overhead',
  },
  {
    category: 'special',
    name: 'POV Shot',
    nameSk: 'Subjektívny záber',
    description: 'First-person perspective',
    descriptionSk: 'Pohľad z prvej osoby',
    prompt: 'point of view shot, first person perspective, through character eyes',
    dramaticUse: 'Character connection, discovery, tension',
    emotionalEffect: 'Immersion, connection, discovery',
    videoPrompt: 'camera: POV, first person',
  },
]

// Movement categories for UI
export const movementCategories = [
  { id: 'basic', name: 'Základné', nameSk: 'Základné', icon: 'Move' },
  { id: 'dolly', name: 'Dolly', nameSk: 'Jazda', icon: 'ArrowRight' },
  { id: 'tracking', name: 'Tracking', nameSk: 'Sledovanie', icon: 'Activity' },
  { id: 'crane', name: 'Crane', nameSk: 'Žeriav', icon: 'ArrowUp' },
  { id: 'orbit', name: 'Orbit', nameSk: 'Oblúk', icon: 'RotateCw' },
  { id: 'zoom', name: 'Zoom', nameSk: 'Zoom', icon: 'ZoomIn' },
  { id: 'handheld', name: 'Handheld', nameSk: 'Z ruky', icon: 'Hand' },
  { id: 'special', name: 'Špeciálne', nameSk: 'Špeciálne', icon: 'Sparkles' },
]

// Emotional mapping for auto-suggestion
export const emotionToCameraMap = {
  tense: ['static', 'slow-zoom-in', 'handheld-natural'],
  romantic: ['arc-left', 'arc-right', 'dolly-in'],
  sad: ['static', 'crane-up', 'dolly-out'],
  triumphant: ['crane-up', '360-orbit', 'low-angle'],
  mysterious: ['dolly-in', 'slow-zoom-in', 'dutch-angle'],
  peaceful: ['static', 'slow-pan', 'crane-down'],
  chaotic: ['shaky-intense', 'crash-zoom', 'handheld-natural'],
  intimate: ['dolly-in', 'close-up-static', 'handheld-natural'],
}
