/**
 * Small Demo Preset - "Stretnutie" (The Meeting)
 * Duration: ~2 minutes
 * A brief romantic encounter at a Slovak vineyard
 * Perfect for testing Higgsfield Cinema Studio
 */

export const smallDemoInfo = {
  id: 'demo-small',
  title: 'Stretnutie',
  titleEn: 'The Meeting',
  size: 'small',
  duration: '~2 minutes',
  genre: 'Romance',
  language: 'Slovak',
  description: {
    sk: 'Krátka romantická scéna - Mária sa po rokoch stretáva s Jakubom vo viniciach.',
    en: 'A short romantic scene - Maria meets Jakub in the vineyard after years apart.',
  },
  stats: {
    actors: 2,
    scenes: 3,
    storyboards: 6,
    dialogueLines: 12,
  },
}

export const smallDemoActors = [
  {
    name: 'Mária',
    age: 32,
    gender: 'female',
    type: 'MAIN',
    description: 'Elegantná klaviristka s melancholickým pohľadom. Vracia sa domov po desiatich rokoch.',
    descriptionEn: 'Elegant pianist with a melancholic gaze. Returns home after ten years.',
    voiceId: 'sk-female-soft',
    imageUrl: '/presets/actors/maria.svg',
    appearance: {
      hair: 'dlhé tmavé vlasy',
      eyes: 'hnedé oči',
      build: 'štíhla postava',
      style: 'elegantný minimalistický štýl',
    },
  },
  {
    name: 'Jakub',
    age: 35,
    gender: 'male',
    type: 'MAIN',
    description: 'Charizmatický vinár so silnými rukami a láskavým úsmevom. Nikdy nezabudol na svoju prvú lásku.',
    descriptionEn: 'Charismatic winemaker with strong hands and a kind smile. Never forgot his first love.',
    voiceId: 'sk-male-warm',
    imageUrl: '/presets/actors/jakub.svg',
    appearance: {
      hair: 'krátke hnedé vlasy',
      eyes: 'zelené oči',
      build: 'atletická postava',
      style: 'pracovné oblečenie, košeľa s vyhrnutými rukávmi',
    },
  },
]

export const smallDemoScenes = [
  {
    order: 1,
    title: 'Arrival at the Vineyard',
    titleSk: 'Príchod do vinice',
    description: 'Maria walks through the vineyard rows at golden hour, memories flooding back.',
    descriptionSk: 'Mária kráča medzi radmi viniča v zlatej hodine, spomienky sa jej vracajú.',
    type: 'ESTABLISHING',
    location: 'Exteriér - Vinica',
    timeOfDay: 'Podvečer / Zlatá hodina',
    mood: 'nostalgic',
    duration: 35,
    category: 'romantic',
    actors: ['Mária'],
    dialogue: [
      {
        actor: 'Mária',
        text: 'Nič sa tu nezmenilo...',
        textEn: 'Nothing has changed here...',
        emotion: 'nostalgic',
        direction: '(šepká pre seba, dotýka sa listov viniča)',
      },
      {
        actor: 'Mária',
        text: 'Desať rokov a vôňa je stále rovnaká.',
        textEn: 'Ten years and the smell is still the same.',
        emotion: 'wistful',
        direction: '(zatvára oči, nadychuje sa)',
      },
    ],
  },
  {
    order: 2,
    title: 'The Unexpected Meeting',
    titleSk: 'Nečakané stretnutie',
    description: 'Jakub appears between the vines, their eyes meet for the first time in a decade.',
    descriptionSk: 'Jakub sa objaví medzi viničom, ich oči sa stretnú po prvýkrát za desať rokov.',
    type: 'DIALOGUE',
    location: 'Exteriér - Vinica',
    timeOfDay: 'Podvečer / Zlatá hodina',
    mood: 'tense',
    duration: 50,
    category: 'dramatic',
    actors: ['Mária', 'Jakub'],
    dialogue: [
      {
        actor: 'Jakub',
        text: 'Mária?',
        textEn: 'Maria?',
        emotion: 'shocked',
        direction: '(zastavuje sa, neveriacky)',
      },
      {
        actor: 'Mária',
        text: 'Jakub... Ahoj.',
        textEn: 'Jakub... Hi.',
        emotion: 'nervous',
        direction: '(neisto sa usmieva)',
      },
      {
        actor: 'Jakub',
        text: 'Desať rokov. Ani jeden telefonát.',
        textEn: 'Ten years. Not a single phone call.',
        emotion: 'hurt',
        direction: '(prichádza bližšie, intenzívny pohľad)',
      },
      {
        actor: 'Mária',
        text: 'Viem. Ospravedlňujem sa. Bála som sa.',
        textEn: 'I know. I am sorry. I was scared.',
        emotion: 'apologetic',
        direction: '(sklopí zrak)',
      },
      {
        actor: 'Jakub',
        text: 'Čoho si sa bála?',
        textEn: 'What were you scared of?',
        emotion: 'curious',
        direction: '(jemnejšie, skúmavo)',
      },
      {
        actor: 'Mária',
        text: 'Že ma ešte stále miluješ.',
        textEn: 'That you still love me.',
        emotion: 'vulnerable',
        direction: '(zdvihne pohľad, slzy v očiach)',
      },
    ],
  },
  {
    order: 3,
    title: 'Sunset Confession',
    titleSk: 'Vyznanie pri západe slnka',
    description: 'Standing together watching the sunset, they begin to reconcile.',
    descriptionSk: 'Stoja spolu a pozerajú sa na západ slnka, začínajú sa zmierovať.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Vinica / Kopec',
    timeOfDay: 'Západ slnka',
    mood: 'romantic',
    duration: 35,
    category: 'romantic',
    actors: ['Mária', 'Jakub'],
    dialogue: [
      {
        actor: 'Jakub',
        text: 'Nikdy som na teba nezabudol, Mária.',
        textEn: 'I never forgot you, Maria.',
        emotion: 'sincere',
        direction: '(berie ju za ruku)',
      },
      {
        actor: 'Mária',
        text: 'Ani ja na teba, Jakub.',
        textEn: 'Neither did I, Jakub.',
        emotion: 'loving',
        direction: '(položí hlavu na jeho rameno)',
      },
      {
        actor: 'Jakub',
        text: 'Tak čo teraz?',
        textEn: 'So what now?',
        emotion: 'hopeful',
        direction: '(pozerá na západ slnka)',
      },
      {
        actor: 'Mária',
        text: 'Teraz... zostávam.',
        textEn: 'Now... I am staying.',
        emotion: 'determined',
        direction: '(usmieva sa, slzy šťastia)',
      },
    ],
  },
]

export const smallDemoStoryboards = [
  {
    id: 'small-sb-1',
    sceneOrder: 1,
    shotNumber: 1,
    prompt: 'Wide establishing shot of Slovak vineyard at golden hour, woman in elegant dress walking between vine rows, cinematic lighting, film grain, 35mm photography, warm sunset colors, nostalgic mood',
    negativePrompt: 'cartoon, anime, low quality, blurry, modern buildings, cars',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'nostalgic',
    lighting: 'golden hour',
    cameraMovement: 'slow dolly forward',
    tags: ['establishing', 'vineyard', 'golden-hour', 'romantic'],
  },
  {
    id: 'small-sb-2',
    sceneOrder: 1,
    shotNumber: 2,
    prompt: 'Close-up of woman hand gently touching grape vine leaves, soft focus background, golden sunlight, intimate moment, cinematic color grading, shallow depth of field',
    negativePrompt: 'cartoon, anime, low quality, harsh lighting',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'intimate',
    lighting: 'golden hour backlight',
    cameraMovement: 'static',
    tags: ['close-up', 'detail', 'emotional'],
  },
  {
    id: 'small-sb-3',
    sceneOrder: 2,
    shotNumber: 1,
    prompt: 'Medium shot of handsome man appearing between vineyard rows, surprised expression, rugged winemaker appearance, rolled up sleeves, golden hour lighting, cinematic composition',
    negativePrompt: 'cartoon, anime, low quality, indoor setting',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'dramatic',
    lighting: 'side lighting golden hour',
    cameraMovement: 'subtle push in',
    tags: ['character-intro', 'dramatic', 'vineyard'],
  },
  {
    id: 'small-sb-4',
    sceneOrder: 2,
    shotNumber: 2,
    prompt: 'Over-the-shoulder shot, woman facing man in vineyard, emotional tension, tears in her eyes, shallow depth of field, vineyard bokeh background, intimate conversation',
    negativePrompt: 'cartoon, anime, low quality, crowded scene',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'emotional',
    lighting: 'soft natural light',
    cameraMovement: 'static',
    tags: ['dialogue', 'emotional', 'two-shot'],
  },
  {
    id: 'small-sb-5',
    sceneOrder: 3,
    shotNumber: 1,
    prompt: 'Wide shot of couple silhouette against dramatic sunset sky, standing on hill overlooking vineyard valley, romantic atmosphere, orange and purple sky, cinematic epic composition',
    negativePrompt: 'cartoon, anime, low quality, rainy, overcast',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'romantic',
    lighting: 'sunset silhouette',
    cameraMovement: 'slow crane up',
    tags: ['romantic', 'sunset', 'silhouette', 'epic'],
  },
  {
    id: 'small-sb-6',
    sceneOrder: 3,
    shotNumber: 2,
    prompt: 'Close-up of hands intertwining, man and woman holding hands, sunset light on skin, wedding rings absent, intimate romantic moment, shallow depth of field, warm color palette',
    negativePrompt: 'cartoon, anime, low quality, cold colors',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'romantic',
    lighting: 'warm sunset rim light',
    cameraMovement: 'static',
    tags: ['close-up', 'romantic', 'detail', 'hands'],
  },
]

export const smallDemoMusic = [
  {
    name: 'Vineyard Sunset',
    prompt: 'Gentle acoustic guitar with soft strings, romantic Slovak folk influence, nostalgic and hopeful, sunset atmosphere, intimate mood',
    style: 'acoustic folk romance',
    mood: 'romantic',
    tempo: 'slow',
    duration: 120,
    category: 'background',
  },
]
