/**
 * Medium Demo Preset - "Návrat" (The Return)
 * Duration: ~5 minutes
 * Maria returns home for her grandmother's funeral
 * Complete story arc with family drama
 */

export const mediumDemoInfo = {
  id: 'demo-medium',
  title: 'Návrat',
  titleEn: 'The Return',
  size: 'medium',
  duration: '~5 minutes',
  genre: 'Drama',
  language: 'Slovak',
  description: {
    sk: 'Mária sa vracia do rodného mesta na pohreb babičky. Stretáva sa so sestrou Elenou a svojou prvou láskou Jakubom.',
    en: 'Maria returns to her hometown for her grandmother\'s funeral. She meets her sister Elena and her first love Jakub.',
  },
  stats: {
    actors: 8,
    scenes: 8,
    storyboards: 18,
    dialogueLines: 45,
  },
}

export const mediumDemoActors = [
  {
    name: 'Mária',
    age: 32,
    gender: 'female',
    type: 'MAIN',
    description: 'Úspešná klaviristka žijúca v zahraničí. Po desiatich rokoch sa vracia domov na pohreb babičky.',
    descriptionEn: 'Successful pianist living abroad. Returns home after ten years for grandmother\'s funeral.',
    voiceId: 'sk-female-soft',
    imageUrl: '/presets/actors/maria.svg',
    appearance: {
      hair: 'dlhé tmavé vlasy',
      eyes: 'hnedé oči',
      build: 'štíhla postava',
      style: 'elegantný minimalistický štýl',
    },
  },
  {
    name: 'Elena',
    age: 28,
    gender: 'female',
    type: 'MAIN',
    description: 'Máriina mladšia sestra, ktorá zostala doma starať sa o babičku. Cíti sa zradená.',
    descriptionEn: 'Maria\'s younger sister who stayed home to care for grandmother. Feels betrayed.',
    voiceId: 'sk-female-strong',
    imageUrl: '/presets/actors/elena.svg',
    appearance: {
      hair: 'stredne dlhé hnedé vlasy',
      eyes: 'modré oči',
      build: 'športová postava',
      style: 'praktické oblečenie',
    },
  },
  {
    name: 'Jakub',
    age: 35,
    gender: 'male',
    type: 'MAIN',
    description: 'Vinár a Máriina prvá láska. Nikdy sa neoženil.',
    descriptionEn: 'Winemaker and Maria\'s first love. Never married.',
    voiceId: 'sk-male-warm',
    imageUrl: '/presets/actors/jakub.svg',
    appearance: {
      hair: 'krátke hnedé vlasy',
      eyes: 'zelené oči',
      build: 'atletická postava',
      style: 'pracovné oblečenie',
    },
  },
  {
    name: 'Otec Peter',
    age: 60,
    gender: 'male',
    type: 'SUPPORTING',
    description: 'Miestny farár, rodinný priateľ, vedie pohrebný obrad.',
    descriptionEn: 'Local priest, family friend, leads the funeral ceremony.',
    voiceId: 'sk-male-elderly',
    imageUrl: '/presets/actors/peter.svg',
    appearance: {
      hair: 'šedivé vlasy',
      eyes: 'sivé oči',
      build: 'stredná postava',
      style: 'kňazský odev',
    },
  },
  {
    name: 'Zuzana',
    age: 55,
    gender: 'female',
    type: 'SUPPORTING',
    description: 'Susedka a rodinná priateľka, pozná všetky tajomstvá.',
    descriptionEn: 'Neighbor and family friend, knows all the secrets.',
    voiceId: 'sk-female-mature',
    imageUrl: '/presets/actors/zuzana.svg',
    appearance: {
      hair: 'krátke blond vlasy',
      eyes: 'hnedé oči',
      build: 'plnšia postava',
      style: 'tradičný vidiecky štýl',
    },
  },
  {
    name: 'Starý Jano',
    age: 75,
    gender: 'male',
    type: 'MINOR',
    description: 'Starý vinár, Jakubov učiteľ, múdry pozorovateľ.',
    descriptionEn: 'Old winemaker, Jakub\'s mentor, wise observer.',
    voiceId: 'sk-male-elderly',
    imageUrl: '/presets/actors/jano.svg',
    appearance: {
      hair: 'biele vlasy',
      eyes: 'modré oči',
      build: 'zhrbená postava',
      style: 'vidiecke oblečenie',
    },
  },
  {
    name: 'Taxikár Milan',
    age: 45,
    gender: 'male',
    type: 'MINOR',
    description: 'Miestny taxikár, vezie Máriu z vlaku.',
    descriptionEn: 'Local taxi driver, picks Maria up from train.',
    voiceId: 'sk-male-casual',
    imageUrl: null,
    appearance: {
      hair: 'rednúce tmavé vlasy',
      eyes: 'hnedé oči',
      build: 'väčšia postava',
      style: 'neformálne oblečenie',
    },
  },
  {
    name: 'Smútočný hosť',
    age: 50,
    gender: 'male',
    type: 'GENERIC',
    description: 'Generický smútočný hosť na pohrebe.',
    descriptionEn: 'Generic funeral guest.',
    voiceId: null,
    imageUrl: null,
    appearance: {
      style: 'čierny oblek',
    },
  },
]

export const mediumDemoScenes = [
  {
    order: 1,
    title: 'Train Arrival',
    titleSk: 'Príchod vlakom',
    description: 'Maria arrives at the small Slovak town train station. Everything looks the same yet feels different.',
    descriptionSk: 'Mária prichádza na malú slovenskú železničnú stanicu. Všetko vyzerá rovnako, ale cíti sa to inak.',
    type: 'ESTABLISHING',
    location: 'Exteriér - Železničná stanica',
    timeOfDay: 'Ráno',
    mood: 'melancholic',
    duration: 30,
    category: 'establishing',
    actors: ['Mária', 'Taxikár Milan'],
    dialogue: [
      {
        actor: 'Taxikár Milan',
        text: 'Vy ste tá Mária? Babkina vnučka?',
        textEn: 'You\'re that Maria? The grandmother\'s granddaughter?',
        emotion: 'curious',
        direction: '(pomáha s kufrom)',
      },
      {
        actor: 'Mária',
        text: 'Áno, to som ja.',
        textEn: 'Yes, that\'s me.',
        emotion: 'tired',
        direction: '(smutný úsmev)',
      },
      {
        actor: 'Taxikár Milan',
        text: 'Celé mesto o vás hovorí. Tá slávna klaviristka.',
        textEn: 'The whole town talks about you. The famous pianist.',
        emotion: 'impressed',
        direction: '(otvára dvere taxíka)',
      },
    ],
  },
  {
    order: 2,
    title: 'The Old House',
    titleSk: 'Starý dom',
    description: 'Maria stands in front of her grandmother\'s house, hesitating to enter.',
    descriptionSk: 'Mária stojí pred babkiným domom a váha, či má vojsť.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Babkin dom',
    timeOfDay: 'Dopoludnie',
    mood: 'nostalgic',
    duration: 25,
    category: 'emotional',
    actors: ['Mária'],
    dialogue: [
      {
        actor: 'Mária',
        text: 'Prepáč, babička. Prepáč, že som neprišla skôr.',
        textEn: 'Sorry, grandma. Sorry I didn\'t come sooner.',
        emotion: 'guilty',
        direction: '(šepká, slzy v očiach)',
      },
    ],
  },
  {
    order: 3,
    title: 'Sister\'s Confrontation',
    titleSk: 'Konfrontácia so sestrou',
    description: 'Elena opens the door. The tension between sisters is immediate.',
    descriptionSk: 'Elena otvára dvere. Napätie medzi sestrami je okamžité.',
    type: 'DIALOGUE',
    location: 'Interiér - Babkin dom / Predsieň',
    timeOfDay: 'Dopoludnie',
    mood: 'tense',
    duration: 45,
    category: 'dramatic',
    actors: ['Mária', 'Elena'],
    dialogue: [
      {
        actor: 'Elena',
        text: 'Tak predsa si prišla.',
        textEn: 'So you came after all.',
        emotion: 'cold',
        direction: '(stojí v dverách, ruky prekrížené)',
      },
      {
        actor: 'Mária',
        text: 'Elena... Ako sa máš?',
        textEn: 'Elena... How are you?',
        emotion: 'hesitant',
        direction: '(pokus o objatie)',
      },
      {
        actor: 'Elena',
        text: 'Ako sa mám? Desať rokov som sa o ňu starala sama!',
        textEn: 'How am I? I took care of her alone for ten years!',
        emotion: 'angry',
        direction: '(odstúpi, odmietne objatie)',
      },
      {
        actor: 'Mária',
        text: 'Viem. Mrzí ma to. Posielala som peniaze...',
        textEn: 'I know. I\'m sorry. I sent money...',
        emotion: 'apologetic',
        direction: '(sklopí zrak)',
      },
      {
        actor: 'Elena',
        text: 'Peniaze! Ona nechcela peniaze, Mária. Chcela teba.',
        textEn: 'Money! She didn\'t want money, Maria. She wanted you.',
        emotion: 'hurt',
        direction: '(slzy hnevu)',
      },
      {
        actor: 'Mária',
        text: 'Môžeme sa o tom porozprávať? Prosím.',
        textEn: 'Can we talk about this? Please.',
        emotion: 'pleading',
        direction: '(krok vpred)',
      },
      {
        actor: 'Elena',
        text: 'Pohreb je zajtra o desiatej. Tvoja izba je pripravená.',
        textEn: 'Funeral is tomorrow at ten. Your room is ready.',
        emotion: 'dismissive',
        direction: '(odchádza)',
      },
    ],
  },
  {
    order: 4,
    title: 'Grandmother\'s Room',
    titleSk: 'Babkina izba',
    description: 'Maria enters grandmother\'s room, finds old photos and a mysterious letter.',
    descriptionSk: 'Mária vchádza do babkinej izby, nachádza staré fotky a záhadný list.',
    type: 'DISCOVERY',
    location: 'Interiér - Babkina izba',
    timeOfDay: 'Popoludnie',
    mood: 'mysterious',
    duration: 35,
    category: 'emotional',
    actors: ['Mária'],
    dialogue: [
      {
        actor: 'Mária',
        text: 'Čo je toto? Komu písala?',
        textEn: 'What is this? Who was she writing to?',
        emotion: 'curious',
        direction: '(drží starý list, mračí sa)',
      },
      {
        actor: 'Mária',
        text: '"Môj milý syn..." Aký syn?',
        textEn: '"My dear son..." What son?',
        emotion: 'confused',
        direction: '(šokovaná)',
      },
    ],
  },
  {
    order: 5,
    title: 'The Funeral',
    titleSk: 'Pohreb',
    description: 'The funeral ceremony. Maria sees Jakub for the first time.',
    descriptionSk: 'Pohrebná ceremónia. Mária prvýkrát vidí Jakuba.',
    type: 'CEREMONY',
    location: 'Exteriér - Cintorín',
    timeOfDay: 'Dopoludnie',
    mood: 'solemn',
    duration: 50,
    category: 'dramatic',
    actors: ['Mária', 'Elena', 'Jakub', 'Otec Peter', 'Zuzana', 'Starý Jano', 'Smútočný hosť'],
    dialogue: [
      {
        actor: 'Otec Peter',
        text: 'Rozlúčme sa s Annou Kováčovou, milujúcou babičkou a dobrou dušou tohto mesta.',
        textEn: 'Let us say goodbye to Anna Kovacova, loving grandmother and good soul of this town.',
        emotion: 'solemn',
        direction: '(pri hrobe)',
      },
      {
        actor: 'Zuzana',
        text: 'Tá Mária z Viedne sa konečne ukázala.',
        textEn: 'That Maria from Vienna finally showed up.',
        emotion: 'gossipy',
        direction: '(šepká susedke)',
      },
      {
        actor: 'Mária',
        text: 'Jakub?',
        textEn: 'Jakub?',
        emotion: 'shocked',
        direction: '(ich oči sa stretnú)',
      },
    ],
  },
  {
    order: 6,
    title: 'After the Funeral',
    titleSk: 'Po pohrebe',
    description: 'Maria and Jakub finally speak. Old feelings resurface.',
    descriptionSk: 'Mária a Jakub sa konečne rozprávajú. Staré city sa vracajú.',
    type: 'DIALOGUE',
    location: 'Exteriér - Cintorín / Odľahlé miesto',
    timeOfDay: 'Popoludnie',
    mood: 'bittersweet',
    duration: 55,
    category: 'romantic',
    actors: ['Mária', 'Jakub'],
    dialogue: [
      {
        actor: 'Jakub',
        text: 'Zdravím, Mária.',
        textEn: 'Hello, Maria.',
        emotion: 'guarded',
        direction: '(prichádza k nej)',
      },
      {
        actor: 'Mária',
        text: 'Jakub. Nevedela som, že prídeš.',
        textEn: 'Jakub. I didn\'t know you would come.',
        emotion: 'surprised',
        direction: '(nervózne)',
      },
      {
        actor: 'Jakub',
        text: 'Tvoja babička bola výnimočná žena. Vždy mi hovorila o tebe.',
        textEn: 'Your grandmother was an exceptional woman. She always told me about you.',
        emotion: 'warm',
        direction: '(jemný úsmev)',
      },
      {
        actor: 'Mária',
        text: 'Vždy?',
        textEn: 'Always?',
        emotion: 'touched',
        direction: '(prekvapená)',
      },
      {
        actor: 'Jakub',
        text: 'Bola na teba hrdá. Aj keď jej chýbala.',
        textEn: 'She was proud of you. Even though she missed you.',
        emotion: 'sincere',
        direction: '(intenzívny pohľad)',
      },
      {
        actor: 'Mária',
        text: 'Jakub, ja... prečo si sa neoženil?',
        textEn: 'Jakub, I... why didn\'t you get married?',
        emotion: 'curious',
        direction: '(neočakávaná otázka)',
      },
      {
        actor: 'Jakub',
        text: 'Myslím, že vieš prečo.',
        textEn: 'I think you know why.',
        emotion: 'meaningful',
        direction: '(dlhý pohľad)',
      },
    ],
  },
  {
    order: 7,
    title: 'Elena\'s Breakdown',
    titleSk: 'Elenin zlom',
    description: 'Late night. Elena finally breaks down and opens up to Maria.',
    descriptionSk: 'Neskoro v noci. Elena sa konečne zrúti a otvorí sa Márii.',
    type: 'EMOTIONAL',
    location: 'Interiér - Kuchyňa',
    timeOfDay: 'Noc',
    mood: 'emotional',
    duration: 45,
    category: 'dramatic',
    actors: ['Mária', 'Elena'],
    dialogue: [
      {
        actor: 'Elena',
        text: 'Nemôžem spať.',
        textEn: 'I can\'t sleep.',
        emotion: 'exhausted',
        direction: '(vchádza do kuchyne)',
      },
      {
        actor: 'Mária',
        text: 'Ani ja. Čaj?',
        textEn: 'Neither can I. Tea?',
        emotion: 'gentle',
        direction: '(nalieva čaj)',
      },
      {
        actor: 'Elena',
        text: 'Prečo si odišla, Mária? Naozaj. Kvôli kariére?',
        textEn: 'Why did you leave, Maria? Really. For your career?',
        emotion: 'vulnerable',
        direction: '(sadá si)',
      },
      {
        actor: 'Mária',
        text: 'Bála som sa. Bála som sa, že tu zostarem a nikdy nedosiahnem svoje sny.',
        textEn: 'I was scared. Scared I would stay here and never achieve my dreams.',
        emotion: 'honest',
        direction: '(priznanie)',
      },
      {
        actor: 'Elena',
        text: 'A ja som sa bála, že tu zostarem sama. A stalo sa to.',
        textEn: 'And I was scared I would stay here alone. And it happened.',
        emotion: 'tearful',
        direction: '(plače)',
      },
      {
        actor: 'Mária',
        text: 'Prepáč mi, Elena. Prosím.',
        textEn: 'Forgive me, Elena. Please.',
        emotion: 'remorseful',
        direction: '(berie ju za ruku)',
      },
      {
        actor: 'Elena',
        text: 'Potrebujem čas. Ale... rada ťa vidím.',
        textEn: 'I need time. But... I\'m glad to see you.',
        emotion: 'softening',
        direction: '(prvý úsmev)',
      },
    ],
  },
  {
    order: 8,
    title: 'Morning Resolution',
    titleSk: 'Ranné rozhodnutie',
    description: 'Maria watches sunrise from grandmother\'s garden, makes a decision.',
    descriptionSk: 'Mária sleduje východ slnka z babkinej záhrady, robí rozhodnutie.',
    type: 'RESOLUTION',
    location: 'Exteriér - Záhrada',
    timeOfDay: 'Svitanie',
    mood: 'hopeful',
    duration: 30,
    category: 'emotional',
    actors: ['Mária', 'Elena'],
    dialogue: [
      {
        actor: 'Elena',
        text: 'Čo robíš tak skoro?',
        textEn: 'What are you doing so early?',
        emotion: 'curious',
        direction: '(prichádza s kávou)',
      },
      {
        actor: 'Mária',
        text: 'Rozmýšľam. Čo keby som zostala dlhšie? Pomohla ti s domom, s dedičstvom.',
        textEn: 'Thinking. What if I stayed longer? Helped you with the house, with the inheritance.',
        emotion: 'hopeful',
        direction: '(otáča sa k nej)',
      },
      {
        actor: 'Elena',
        text: 'Naozaj?',
        textEn: 'Really?',
        emotion: 'surprised',
        direction: '(neveriacky)',
      },
      {
        actor: 'Mária',
        text: 'Babička nám niečo zanechala. Nielen tento dom. Zanechala nám príbeh, ktorý potrebujeme pochopiť.',
        textEn: 'Grandma left us something. Not just this house. She left us a story we need to understand.',
        emotion: 'determined',
        direction: '(drží list)',
      },
      {
        actor: 'Elena',
        text: 'Čo je v tom liste?',
        textEn: 'What\'s in that letter?',
        emotion: 'intrigued',
        direction: '(záujem)',
      },
      {
        actor: 'Mária',
        text: 'Tajomstvo. Naše rodinné tajomstvo.',
        textEn: 'A secret. Our family secret.',
        emotion: 'mysterious',
        direction: '(východ slnka osvetľuje ich tváre)',
      },
    ],
  },
]

export const mediumDemoStoryboards = [
  // Scene 1 - Train Arrival
  {
    id: 'med-sb-1',
    sceneOrder: 1,
    shotNumber: 1,
    prompt: 'Wide shot of small Slovak town train station, morning mist, woman with suitcase stepping off train, vintage European architecture, cinematic, film grain, nostalgic mood',
    negativePrompt: 'cartoon, anime, modern station, crowded',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'melancholic',
    lighting: 'soft morning light',
    cameraMovement: 'static wide',
    tags: ['establishing', 'arrival', 'station'],
  },
  {
    id: 'med-sb-2',
    sceneOrder: 1,
    shotNumber: 2,
    prompt: 'Medium shot of elegant woman 30s looking around small town station, suitcase beside her, taxi in background, nostalgic expression, European setting',
    negativePrompt: 'cartoon, anime, happy expression',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'pensive',
    lighting: 'natural daylight',
    cameraMovement: 'subtle push in',
    tags: ['character', 'arrival'],
  },
  // Scene 2 - Old House
  {
    id: 'med-sb-3',
    sceneOrder: 2,
    shotNumber: 1,
    prompt: 'Establishing shot of traditional Slovak countryside house with garden, woman standing at gate looking at house, emotional moment, soft lighting, film grain',
    negativePrompt: 'cartoon, anime, modern house, ugly',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'nostalgic',
    lighting: 'soft diffused light',
    cameraMovement: 'slow dolly in',
    tags: ['establishing', 'house', 'emotional'],
  },
  // Scene 3 - Confrontation
  {
    id: 'med-sb-4',
    sceneOrder: 3,
    shotNumber: 1,
    prompt: 'Two women facing each other in doorway of old house, tense body language, one with crossed arms, dramatic lighting from inside, European interior',
    negativePrompt: 'cartoon, anime, happy, hugging',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'tense',
    lighting: 'dramatic contrast',
    cameraMovement: 'static',
    tags: ['confrontation', 'dramatic', 'two-shot'],
  },
  {
    id: 'med-sb-5',
    sceneOrder: 3,
    shotNumber: 2,
    prompt: 'Close-up of woman face, tears of anger, emotional confrontation, shallow depth of field, cinematic portrait',
    negativePrompt: 'cartoon, anime, smiling, happy',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'emotional',
    lighting: 'soft key light',
    cameraMovement: 'static',
    tags: ['close-up', 'emotional', 'portrait'],
  },
  // Scene 4 - Grandmother's Room
  {
    id: 'med-sb-6',
    sceneOrder: 4,
    shotNumber: 1,
    prompt: 'Interior of old woman bedroom, traditional Slovak decor, woman looking at old photographs on dresser, dust particles in light beam, nostalgic atmosphere',
    negativePrompt: 'cartoon, anime, modern room, messy',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'mysterious',
    lighting: 'single window light beam',
    cameraMovement: 'slow pan',
    tags: ['interior', 'discovery', 'nostalgic'],
  },
  {
    id: 'med-sb-7',
    sceneOrder: 4,
    shotNumber: 2,
    prompt: 'Extreme close-up of hands holding old handwritten letter, elegant female hands, vintage paper, dramatic focus, mystery element',
    negativePrompt: 'cartoon, anime, printed letter, modern paper',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'mysterious',
    lighting: 'soft natural light',
    cameraMovement: 'static',
    tags: ['close-up', 'prop', 'mystery'],
  },
  // Scene 5 - Funeral
  {
    id: 'med-sb-8',
    sceneOrder: 5,
    shotNumber: 1,
    prompt: 'Wide shot of traditional Slovak cemetery, group of people in black at funeral, priest speaking, small town setting, solemn atmosphere, overcast sky',
    negativePrompt: 'cartoon, anime, sunny, happy, colorful',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'solemn',
    lighting: 'overcast diffused',
    cameraMovement: 'slow crane down',
    tags: ['funeral', 'establishing', 'solemn'],
  },
  {
    id: 'med-sb-9',
    sceneOrder: 5,
    shotNumber: 2,
    prompt: 'Medium shot of woman in black dress at funeral suddenly seeing someone, surprised expression, cemetery background with mourners, dramatic moment',
    negativePrompt: 'cartoon, anime, happy, colorful clothes',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'dramatic',
    lighting: 'overcast natural',
    cameraMovement: 'subtle push in',
    tags: ['reaction', 'dramatic', 'funeral'],
  },
  {
    id: 'med-sb-10',
    sceneOrder: 5,
    shotNumber: 3,
    prompt: 'Over-shoulder shot revealing handsome man 35 at funeral, eyes meeting across crowd, romantic tension, cemetery setting, cinematic composition',
    negativePrompt: 'cartoon, anime, ugly, unfocused',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'romantic tension',
    lighting: 'soft overcast',
    cameraMovement: 'static',
    tags: ['reveal', 'romantic', 'two-shot'],
  },
  // Scene 6 - After Funeral
  {
    id: 'med-sb-11',
    sceneOrder: 6,
    shotNumber: 1,
    prompt: 'Two people talking alone in quiet corner of cemetery, man and woman, intimate conversation, trees in background, emotional atmosphere',
    negativePrompt: 'cartoon, anime, crowded, happy',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'intimate',
    lighting: 'soft afternoon light',
    cameraMovement: 'slow orbit',
    tags: ['dialogue', 'romantic', 'two-shot'],
  },
  {
    id: 'med-sb-12',
    sceneOrder: 6,
    shotNumber: 2,
    prompt: 'Close-up of man and woman faces in profile, intense eye contact, unspoken feelings, shallow depth of field, romantic tension, cinematic portrait',
    negativePrompt: 'cartoon, anime, kissing, far apart',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'romantic',
    lighting: 'soft backlight',
    cameraMovement: 'static',
    tags: ['close-up', 'romantic', 'portrait'],
  },
  // Scene 7 - Kitchen Night
  {
    id: 'med-sb-13',
    sceneOrder: 7,
    shotNumber: 1,
    prompt: 'Interior of traditional Slovak kitchen at night, two women sitting at table with tea, warm lamp light, emotional conversation, intimate atmosphere',
    negativePrompt: 'cartoon, anime, modern kitchen, bright',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'intimate',
    lighting: 'warm practical lamp',
    cameraMovement: 'static wide',
    tags: ['interior', 'night', 'emotional'],
  },
  {
    id: 'med-sb-14',
    sceneOrder: 7,
    shotNumber: 2,
    prompt: 'Medium shot of younger woman crying at kitchen table, older sister reaching for her hand, emotional reconciliation, warm lighting',
    negativePrompt: 'cartoon, anime, happy, laughing',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'emotional',
    lighting: 'warm key light',
    cameraMovement: 'subtle push in',
    tags: ['emotional', 'sisters', 'reconciliation'],
  },
  {
    id: 'med-sb-15',
    sceneOrder: 7,
    shotNumber: 3,
    prompt: 'Close-up of two hands clasping across kitchen table, sisters reconciling, tea cups nearby, warm intimate lighting, emotional detail shot',
    negativePrompt: 'cartoon, anime, cold colors',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'tender',
    lighting: 'warm practical light',
    cameraMovement: 'static',
    tags: ['detail', 'hands', 'emotional'],
  },
  // Scene 8 - Morning Resolution
  {
    id: 'med-sb-16',
    sceneOrder: 8,
    shotNumber: 1,
    prompt: 'Wide shot of woman standing in garden at sunrise, traditional Slovak house in background, hopeful atmosphere, golden morning light, new beginning mood',
    negativePrompt: 'cartoon, anime, sunset, dark',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'hopeful',
    lighting: 'golden sunrise',
    cameraMovement: 'slow crane up',
    tags: ['sunrise', 'hopeful', 'establishing'],
  },
  {
    id: 'med-sb-17',
    sceneOrder: 8,
    shotNumber: 2,
    prompt: 'Two sisters standing together in garden sunrise, first genuine smiles, reconciliation, golden light on faces, hopeful new chapter',
    negativePrompt: 'cartoon, anime, arguing, dark',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'hopeful',
    lighting: 'warm sunrise',
    cameraMovement: 'static',
    tags: ['sisters', 'reconciliation', 'hopeful'],
  },
  {
    id: 'med-sb-18',
    sceneOrder: 8,
    shotNumber: 3,
    prompt: 'Close-up of woman holding old letter against sunrise light, mysterious secret, silhouette edge, dramatic ending shot, cinematic composition',
    negativePrompt: 'cartoon, anime, dark, night',
    resolution: '1920x1080',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'mysterious',
    lighting: 'sunrise backlight',
    cameraMovement: 'slow push in',
    tags: ['close-up', 'mystery', 'ending'],
  },
]

export const mediumDemoMusic = [
  {
    name: 'Homecoming',
    prompt: 'Melancholic piano with subtle strings, Slovak folk undertones, nostalgic return home feeling, bittersweet emotions',
    style: 'orchestral folk',
    mood: 'melancholic',
    tempo: 'slow',
    duration: 90,
    category: 'background',
  },
  {
    name: 'Family Tensions',
    prompt: 'Tense atmospheric music, sparse piano notes, building tension, family drama, unresolved conflict',
    style: 'dramatic ambient',
    mood: 'tense',
    tempo: 'slow',
    duration: 60,
    category: 'dramatic',
  },
  {
    name: 'New Dawn',
    prompt: 'Hopeful piano melody building to strings, sunrise feeling, reconciliation theme, emotional resolution, uplifting ending',
    style: 'orchestral',
    mood: 'hopeful',
    tempo: 'moderate',
    duration: 75,
    category: 'resolution',
  },
]
