/**
 * Demo Scene Presets for FilmFlow AI
 * Slovak Drama: "Stratené Srdcia" (Lost Hearts)
 *
 * Full movie structure with 35 scenes across 5 acts
 * 200+ dialogue lines for realistic 30-minute short film
 */

export const demoScenes = [
  // ==========================================
  // AKT 1: NÁVRAT (THE RETURN) - Scenes 1-7
  // ==========================================
  {
    title: 'Úvodné titulky',
    titleSk: 'Úvodné titulky',
    description: 'Opening credits over sweeping aerial shots of Slovak countryside. Vineyards in autumn colors, small town with church spire.',
    descriptionSk: 'Úvodné titulky nad leteckými zábermi slovenskej krajiny. Vinice v jesenných farbách, malé mestečko s kostolnou vežou.',
    type: 'ESTABLISHING',
    location: 'Exteriér - Slovenská krajina',
    timeOfDay: 'Ráno',
    mood: 'nostalgic',
    duration: 90,
    order: 1,
    category: 'opening',
    dialogue: [],
    actors: [],
  },
  {
    title: 'Príchod vlaku',
    titleSk: 'Príchod vlaku',
    description: 'Maria steps off the train at a small Slovak station. She carries a small suitcase and looks around, memories flooding back.',
    descriptionSk: 'Mária vystupuje z vlaku na malej slovenskej stanici. Nesie malý kufor a rozhliadne sa, spomienky ju zaplaví.',
    type: 'ESTABLISHING',
    location: 'Exteriér - Železničná stanica',
    timeOfDay: 'Popoludnie',
    mood: 'melancholic',
    duration: 45,
    order: 2,
    category: 'drama',
    dialogue: [
      { actor: 'Mária Kováčová', text: '(k sebe) Desať rokov. Desať rokov som tu nebola.', emotion: 'reflective' },
    ],
    actors: ['Mária Kováčová'],
  },
  {
    title: 'Prechádzka mestom',
    titleSk: 'Prechádzka mestom',
    description: 'Maria walks through the familiar streets. She passes the old bakery, the town square, people who recognize her.',
    descriptionSk: 'Mária kráča známymi ulicami. Prechádza okolo starej pekárne, námestia, ľudí, ktorí ju spoznávajú.',
    type: 'ESTABLISHING',
    location: 'Exteriér - Námestie',
    timeOfDay: 'Popoludnie',
    mood: 'nostalgic',
    duration: 60,
    order: 3,
    category: 'drama',
    dialogue: [
      { actor: 'Pani Horváthová', text: 'Máriačka? Si to ty? Božemôj, ako si vyrástla!', emotion: 'surprised' },
      { actor: 'Mária Kováčová', text: 'Dobrý deň, pani Horváthová. Áno, som to ja.', emotion: 'polite' },
      { actor: 'Pani Horváthová', text: 'Tak teda... naša slávna klaviristka sa vrátila. Babička by bola hrdá.', emotion: 'warm' },
      { actor: 'Mária Kováčová', text: 'Ďakujem. Je mi ľúto, že som nestihla...', emotion: 'sad' },
      { actor: 'Pani Horváthová', text: 'Ticho, dievča. Nestratila si čas. Žila si svoj život.', emotion: 'understanding' },
    ],
    actors: ['Mária Kováčová', 'Pani Horváthová'],
  },
  {
    title: 'Prvý pohľad na Jakuba',
    titleSk: 'Prvý pohľad na Jakuba',
    description: 'Maria walks through town and spots Jakub loading wine crates. Their eyes meet. Time seems to stop. Neither knows what to say.',
    descriptionSk: 'Mária kráča mestom a zbadá Jakuba, ktorý nakladá debny s vínom. Ich pohľady sa stretnú. Čas akoby zastal. Ani jeden nevie, čo povedať.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Námestie',
    timeOfDay: 'Popoludnie',
    mood: 'tense',
    duration: 60,
    order: 4,
    category: 'romantic',
    dialogue: [
      { actor: 'Jakub Novák', text: 'Mária...', emotion: 'shocked' },
      { actor: 'Mária Kováčová', text: 'Jakub. Dlho sme sa nevideli.', emotion: 'nervous' },
      { actor: 'Jakub Novák', text: 'Desať rokov. Počítal som.', emotion: 'bitter-sweet' },
      { actor: 'Mária Kováčová', text: 'Ja... prišla som na pohreb.', emotion: 'awkward' },
      { actor: 'Jakub Novák', text: 'Viem. Celé mesto vie. Tvoja babička... bola výnimočná žena.', emotion: 'sympathetic' },
      { actor: 'Mária Kováčová', text: 'Bola. Ďakujem, Jakub.', emotion: 'grateful' },
    ],
    actors: ['Mária Kováčová', 'Jakub Novák'],
  },
  {
    title: 'Stretnutie so sestrou',
    titleSk: 'Stretnutie so sestrou',
    description: 'Elena opens the door to the family home. Her expression is cold. She lets Maria in without a word.',
    descriptionSk: 'Elena otvára dvere rodinného domu. Jej výraz je chladný. Pustí Máriu dovnútra bez slova.',
    type: 'DIALOGUE',
    location: 'Interiér - Rodinný dom, vstupná hala',
    timeOfDay: 'Večer',
    mood: 'tense',
    duration: 90,
    order: 5,
    category: 'drama',
    dialogue: [
      { actor: 'Elena Kováčová', text: 'Tak si predsa prišla.', emotion: 'cold' },
      { actor: 'Mária Kováčová', text: 'Prišla som na pohreb našej babičky. Som tu kvôli nej.', emotion: 'defensive' },
      { actor: 'Elena Kováčová', text: 'Teraz. Teraz si tu kvôli nej. Kde si bola, keď umierala?', emotion: 'angry' },
      { actor: 'Mária Kováčová', text: 'Nebola som pri telefóne, Elena. Nedostala som správu včas.', emotion: 'guilty' },
      { actor: 'Elena Kováčová', text: 'Správu? Volala som ti pätnásťkrát! Pätnásťkrát!', emotion: 'furious' },
      { actor: 'Mária Kováčová', text: 'Bola som na turné. Hranice, letisko, skúšky...', emotion: 'explaining' },
      { actor: 'Elena Kováčová', text: 'Vždy máš výhovorky. Vždy. Tvoja izba je hore. Pohreb je zajtra o deviatej.', emotion: 'dismissive' },
    ],
    actors: ['Mária Kováčová', 'Elena Kováčová'],
  },
  {
    title: 'Babičkina izba',
    titleSk: 'Babičkina izba',
    description: 'Maria enters her grandmother\'s room alone. Everything is preserved as it was. She finds an old photo of herself as a child with her grandmother.',
    descriptionSk: 'Mária vchádza sama do babičkinej izby. Všetko je zachované tak, ako bolo. Nájde starú fotografiu seba ako dieťa s babičkou.',
    type: 'EMOTIONAL',
    location: 'Interiér - Babičkina izba',
    timeOfDay: 'Noc',
    mood: 'sad',
    duration: 75,
    order: 6,
    category: 'emotional',
    dialogue: [
      { actor: 'Mária Kováčová', text: '(šepká) Prepáč, babička. Prepáč, že som tu nebola.', emotion: 'crying' },
      { actor: 'Mária Kováčová', text: 'Vždy si ma učila, že rodina je najdôležitejšia. A ja som utiekla.', emotion: 'regretful' },
      { actor: 'Mária Kováčová', text: 'Pamätáš si túto fotografiu? Bola som taká malá. Taká šťastná.', emotion: 'nostalgic' },
    ],
    actors: ['Mária Kováčová'],
  },
  {
    title: 'Nočné spomienky',
    titleSk: 'Nočné spomienky',
    description: 'Maria lies awake in her old room. She hears sounds of the house, remembers her childhood here.',
    descriptionSk: 'Mária leží v starej izbe a nemôže zaspať. Počuje zvuky domu, spomína na detstvo.',
    type: 'EMOTIONAL',
    location: 'Interiér - Máriina stará izba',
    timeOfDay: 'Noc',
    mood: 'melancholic',
    duration: 60,
    order: 7,
    category: 'emotional',
    dialogue: [
      { actor: 'Mária Kováčová', text: '(vnútorný monológ) Všetko je rovnaké. A predsa úplne iné.', emotion: 'reflective' },
      { actor: 'Mária Kováčová', text: 'Táto izba. Tento dom. Tieto steny ma poznajú lepšie než ja sama.', emotion: 'introspective' },
    ],
    actors: ['Mária Kováčová'],
  },

  // ==========================================
  // AKT 2: KONFRONTÁCIE (CONFRONTATIONS) - Scenes 8-14
  // ==========================================
  {
    title: 'Pohreb',
    titleSk: 'Pohreb',
    description: 'Funeral at the local church. The whole town attends. Maria and Elena stand on opposite sides. Jakub watches from afar.',
    descriptionSk: 'Pohreb v miestnom kostole. Celé mesto sa zúčastňuje. Mária a Elena stoja na opačných stranách. Jakub sleduje z diaľky.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Cintorín',
    timeOfDay: 'Ráno',
    mood: 'somber',
    duration: 120,
    order: 8,
    category: 'emotional',
    dialogue: [
      { actor: 'Peter Molnár', text: 'Anna Kováčová bola svetlom tohto mesta. Jej dobrota pretrvá v nás všetkých.', emotion: 'solemn' },
      { actor: 'Peter Molnár', text: 'Bola matkou pre siroty, babičkou pre všetkých, priateľkou pre každého.', emotion: 'reverent' },
      { actor: 'Peter Molnár', text: 'Zanechala nám viac než spomienky. Zanechala nám príklad.', emotion: 'inspiring' },
      { actor: 'Zuzana Bieliková', text: '(šepká Elene) Drž sa, zlatko. Drž sa.', emotion: 'supportive' },
    ],
    actors: ['Mária Kováčová', 'Elena Kováčová', 'Jakub Novák', 'Peter Molnár', 'Zuzana Bieliková'],
  },
  {
    title: 'Pri hrobe',
    titleSk: 'Pri hrobe',
    description: 'After the funeral, Maria stays at the grave. Jakub approaches her.',
    descriptionSk: 'Po pohrebe zostane Mária pri hrobe. Jakub k nej pristúpi.',
    type: 'DIALOGUE',
    location: 'Exteriér - Cintorín',
    timeOfDay: 'Ráno',
    mood: 'sad',
    duration: 60,
    order: 9,
    category: 'romantic',
    dialogue: [
      { actor: 'Jakub Novák', text: 'Pamätám si, ako nám piekla koláče. Každú nedeľu.', emotion: 'nostalgic' },
      { actor: 'Mária Kováčová', text: 'S orechami a medom. Tvoje obľúbené.', emotion: 'soft' },
      { actor: 'Jakub Novák', text: 'Pamätáš si.', emotion: 'surprised' },
      { actor: 'Mária Kováčová', text: 'Na niektoré veci sa nedá zabudnúť, Jakub.', emotion: 'meaningful' },
      { actor: 'Jakub Novák', text: 'Nie. Na niektoré nie.', emotion: 'intense' },
    ],
    actors: ['Mária Kováčová', 'Jakub Novák'],
  },
  {
    title: 'Kar v kaviarni',
    titleSk: 'Kar v kaviarni',
    description: 'Wake at Elena\'s café. Townspeople offer condolences. Martin appears, a mysterious stranger no one recognizes.',
    descriptionSk: 'Kar v Eleninej kaviarni. Ľudia z mesta vyjadrujú sústrasť. Objaví sa Martin, tajomný cudzinec, ktorého nikto nepozná.',
    type: 'DIALOGUE',
    location: 'Interiér - Kaviareň',
    timeOfDay: 'Popoludnie',
    mood: 'mysterious',
    duration: 90,
    order: 10,
    category: 'mystery',
    dialogue: [
      { actor: 'Zuzana Bieliková', text: '(šepká Elene) Kto je tamten? Nikdy som ho tu nevidela.', emotion: 'curious' },
      { actor: 'Elena Kováčová', text: 'Netuším. Možno nejaký vzdialený príbuzný.', emotion: 'puzzled' },
      { actor: 'Martin Horváth', text: '(k Márii) Moja úprimná sústrasť. Vaša babička bola výnimočná žena.', emotion: 'charming' },
      { actor: 'Mária Kováčová', text: 'Poznali ste ju?', emotion: 'surprised' },
      { actor: 'Martin Horváth', text: 'Povedzme, že naše rodiny majú spoločnú históriu.', emotion: 'mysterious' },
      { actor: 'Mária Kováčová', text: 'Prepáčte, nerozumiem. Kto ste?', emotion: 'confused' },
      { actor: 'Martin Horváth', text: 'Martin. Martin Horváth. Možno si o mne niekedy porozprávame.', emotion: 'cryptic' },
    ],
    actors: ['Mária Kováčová', 'Martin Horváth', 'Elena Kováčová', 'Zuzana Bieliková'],
  },
  {
    title: 'Elena a Tomáš',
    titleSk: 'Elena a Tomáš',
    description: 'Elena and her boyfriend Tomáš argue in private. Their relationship is strained.',
    descriptionSk: 'Elena a jej priateľ Tomáš sa hádajú v súkromí. Ich vzťah je napätý.',
    type: 'DIALOGUE',
    location: 'Interiér - Zákulisie kaviarne',
    timeOfDay: 'Popoludnie',
    mood: 'tense',
    duration: 75,
    order: 11,
    category: 'drama',
    dialogue: [
      { actor: 'Tomáš Kráľ', text: 'Nemôžeš všetko niesť na svojich pleciach, Elena.', emotion: 'concerned' },
      { actor: 'Elena Kováčová', text: 'A kto to má niesť? Ty? Mária? Tá, čo utiekla?', emotion: 'bitter' },
      { actor: 'Tomáš Kráľ', text: 'Nie je to jej chyba, že odišla za kariérou.', emotion: 'reasonable' },
      { actor: 'Elena Kováčová', text: 'Brániš ju? Teraz ju brániš?', emotion: 'hurt' },
      { actor: 'Tomáš Kráľ', text: 'Nebránim ju. Snažím sa ti pomôcť.', emotion: 'frustrated' },
      { actor: 'Elena Kováčová', text: 'Tak mi pomôž tým, že ma necháš na pokoji.', emotion: 'exhausted' },
    ],
    actors: ['Elena Kováčová', 'Tomáš Kráľ'],
  },
  {
    title: 'Nočný rozhovor sestier',
    titleSk: 'Nočný rozhovor sestier',
    description: 'Late night. Elena and Maria finally talk. Years of resentment come pouring out.',
    descriptionSk: 'Neskorá noc. Elena a Mária si konečne pohovoria. Roky nevraživosti sa vylievajú.',
    type: 'DIALOGUE',
    location: 'Interiér - Kuchyňa',
    timeOfDay: 'Noc',
    mood: 'intense',
    duration: 180,
    order: 12,
    category: 'drama',
    dialogue: [
      { actor: 'Elena Kováčová', text: 'Vieš, čo mi povedala pred smrťou? Pýtala sa na teba. Každý deň.', emotion: 'bitter' },
      { actor: 'Mária Kováčová', text: 'Myslíš, že mi to nechýba? Že ma to netrápi?', emotion: 'defensive' },
      { actor: 'Elena Kováčová', text: 'Nie. Nemyslím. Ty si utiekla. Ja som tu zostala zbierať črepiny.', emotion: 'angry' },
      { actor: 'Mária Kováčová', text: 'Utiekla som, pretože som tu nemohla dýchať! Všetko mi tu pripomínalo...', emotion: 'emotional' },
      { actor: 'Elena Kováčová', text: 'Jakuba? Takže kvôli rozchodu si zanechala celú rodinu?', emotion: 'accusatory' },
      { actor: 'Mária Kováčová', text: 'Nebolo to len o Jakubovi! Bola som tu len dcéra, ktorá hrá na klavíri.', emotion: 'revealing' },
      { actor: 'Elena Kováčová', text: 'A ja som bola dcéra, ktorá nehrá na nič. Len varí a upratuje.', emotion: 'hurt' },
      { actor: 'Mária Kováčová', text: 'Elena... nikdy som to tak nemyslela.', emotion: 'apologetic' },
      { actor: 'Elena Kováčová', text: 'Nemyslela si vôbec. To bol problém.', emotion: 'resigned' },
    ],
    actors: ['Mária Kováčová', 'Elena Kováčová'],
  },
  {
    title: 'Vinárstvo',
    titleSk: 'Vinárstvo',
    description: 'Jakub shows his winery to Martin, who claims to be interested in buying. Maria arrives unexpectedly.',
    descriptionSk: 'Jakub ukazuje svoje vinárstvo Martinovi, ktorý tvrdí, že má záujem o kúpu. Nečakane príde Mária.',
    type: 'DIALOGUE',
    location: 'Interiér - Vínna pivnica',
    timeOfDay: 'Popoludnie',
    mood: 'tense',
    duration: 120,
    order: 13,
    category: 'drama',
    dialogue: [
      { actor: 'Martin Horváth', text: 'Výborné terroir. Váš otec by bol hrdý.', emotion: 'appreciative' },
      { actor: 'Jakub Novák', text: 'Poznal ste môjho otca?', emotion: 'suspicious' },
      { actor: 'Martin Horváth', text: 'Povesti o Novákových vínach sa šíria ďaleko.', emotion: 'evasive' },
      { actor: 'Jakub Novák', text: 'Viete veľa o tomto meste. Pre cudzinca.', emotion: 'probing' },
      { actor: 'Martin Horváth', text: 'Nie som taký cudzinec, ako by sa mohlo zdať.', emotion: 'mysterious' },
      { actor: 'Mária Kováčová', text: '(vstupuje) Prepáčte, nevedela som, že máš návštevu.', emotion: 'awkward' },
      { actor: 'Jakub Novák', text: 'Mária. Čo tu robíš?', emotion: 'surprised' },
      { actor: 'Mária Kováčová', text: 'Elena ma poslala. Potrebuje víno na záver karu.', emotion: 'explaining' },
    ],
    actors: ['Jakub Novák', 'Martin Horváth', 'Mária Kováčová'],
  },
  {
    title: 'Spomienka - Prvý bozk',
    titleSk: 'Spomienka - Prvý bozk',
    description: 'Flashback: Young Maria and Jakub share their first kiss among the vineyards. Golden hour, innocent love.',
    descriptionSk: 'Flashback: Mladá Mária a Jakub si vymieňajú prvý bozk medzi vinicami. Zlatá hodina, nevinná láska.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Vinice',
    timeOfDay: 'Západ slnka',
    mood: 'romantic',
    duration: 60,
    order: 14,
    category: 'romantic',
    dialogue: [
      { actor: 'Jakub Novák', text: '(mladý) Sľúb mi, že odtiaľto nikdy neodídeš.', emotion: 'loving' },
      { actor: 'Mária Kováčová', text: '(mladá) Sľubujem. Navždy tu budem s tebou.', emotion: 'loving' },
      { actor: 'Jakub Novák', text: '(mladý) Navždy je dosť dlho.', emotion: 'playful' },
      { actor: 'Mária Kováčová', text: '(mladá) Nie dosť dlho pre nás.', emotion: 'romantic' },
    ],
    actors: ['Mária Kováčová', 'Jakub Novák'],
  },

  // ==========================================
  // AKT 3: TAJOMSTVÁ (SECRETS) - Scenes 15-21
  // ==========================================
  {
    title: 'Nájdený list',
    titleSk: 'Nájdený list',
    description: 'Maria finds an old letter hidden in her grandmother\'s belongings. The contents shock her.',
    descriptionSk: 'Mária nájde starý list ukrytý v babičkiných veciach. Jeho obsah ju šokuje.',
    type: 'DIALOGUE',
    location: 'Interiér - Babičkina izba',
    timeOfDay: 'Popoludnie',
    mood: 'shocking',
    duration: 90,
    order: 15,
    category: 'mystery',
    dialogue: [
      { actor: 'Babička Anna', text: '(voice-over, z listu) Môj milý, toto tajomstvo musím vziať do hrobu. Ale ak to niekedy čítaš, vedz, že Mária nie je...', emotion: 'serious' },
      { actor: 'Mária Kováčová', text: 'Čo to má znamenať? Čo nie som?', emotion: 'confused' },
      { actor: 'Mária Kováčová', text: 'List je nedokončený. Prečo je nedokončený?', emotion: 'frustrated' },
      { actor: 'Mária Kováčová', text: 'Babička, čo si mi chcela povedať?', emotion: 'desperate' },
    ],
    actors: ['Mária Kováčová', 'Babička Anna'],
  },
  {
    title: 'Pátranie v archíve',
    titleSk: 'Pátranie v archíve',
    description: 'Maria searches through old family documents, photos, and letters in the attic.',
    descriptionSk: 'Mária prehľadáva staré rodinné dokumenty, fotografie a listy na povale.',
    type: 'DIALOGUE',
    location: 'Interiér - Povala',
    timeOfDay: 'Večer',
    mood: 'mysterious',
    duration: 90,
    order: 16,
    category: 'mystery',
    dialogue: [
      { actor: 'Mária Kováčová', text: 'Tieto fotografie... nikdy som ich nevidela.', emotion: 'curious' },
      { actor: 'Mária Kováčová', text: 'Kto je tento muž? Stojí vedľa mamy na každej fotografii.', emotion: 'puzzled' },
      { actor: 'Mária Kováčová', text: 'Toto nie je otec. Kto to je?', emotion: 'alarmed' },
    ],
    actors: ['Mária Kováčová'],
  },
  {
    title: 'Konfrontácia s farárom',
    titleSk: 'Konfrontácia s farárom',
    description: 'Maria confronts Father Peter about the letter. He reluctantly reveals part of the truth.',
    descriptionSk: 'Mária konfrontuje farára Petra ohľadom listu. Neochotne odhalí časť pravdy.',
    type: 'DIALOGUE',
    location: 'Interiér - Kostol',
    timeOfDay: 'Večer',
    mood: 'tense',
    duration: 150,
    order: 17,
    category: 'drama',
    dialogue: [
      { actor: 'Mária Kováčová', text: 'Viete, čo je v tomto liste. Poznám vás celý život. Vidím to na vás.', emotion: 'demanding' },
      { actor: 'Peter Molnár', text: 'Niektoré tajomstvá sú lepšie pochované.', emotion: 'conflicted' },
      { actor: 'Mária Kováčová', text: 'Mám právo vedieť!', emotion: 'desperate' },
      { actor: 'Peter Molnár', text: 'Tvoja matka... nebola tou, za koho sa vydávala. A ty... ty máš otca, o ktorom nič nevieš.', emotion: 'grave' },
      { actor: 'Mária Kováčová', text: 'Čo tým myslíte? Môj otec zomrel, keď som mala päť rokov!', emotion: 'shocked' },
      { actor: 'Peter Molnár', text: 'Muž, ktorého si poznala ako otca... nebol tvoj biologický otec.', emotion: 'heavy' },
      { actor: 'Mária Kováčová', text: 'To nie je pravda. To nemôže byť pravda.', emotion: 'denial' },
      { actor: 'Peter Molnár', text: 'Pravda je zložitejšia, než si kedy myslela, dievča moje.', emotion: 'sympathetic' },
    ],
    actors: ['Mária Kováčová', 'Peter Molnár'],
  },
  {
    title: 'Martinova pravá tvár',
    titleSk: 'Martinova pravá tvár',
    description: 'Martin reveals his true identity to Maria. He claims to be her half-brother.',
    descriptionSk: 'Martin odhalí Márii svoju skutočnú identitu. Tvrdí, že je jej nevlastný brat.',
    type: 'DIALOGUE',
    location: 'Exteriér - Lavička v parku',
    timeOfDay: 'Súmrak',
    mood: 'shocking',
    duration: 180,
    order: 18,
    category: 'drama',
    dialogue: [
      { actor: 'Martin Horváth', text: 'Náš otec bol rakúsky businessman. Mal dve rodiny. Tvoja matka bola jeho tajná láska.', emotion: 'matter-of-fact' },
      { actor: 'Mária Kováčová', text: 'To nie je možné. Môj otec... ten, ktorý ma vychoval...', emotion: 'disbelief' },
      { actor: 'Martin Horváth', text: 'Nebol tvoj biologický otec. Ale miloval ťa ako vlastnú. To je viac, než mal kto z nás.', emotion: 'bitter' },
      { actor: 'Mária Kováčová', text: 'Prečo mi to hovoríš? Prečo teraz?', emotion: 'overwhelmed' },
      { actor: 'Martin Horváth', text: 'Pretože náš otec zomrel. Pred mesiacom. A ty si jeho dedička.', emotion: 'revealing' },
      { actor: 'Mária Kováčová', text: 'Dedička? Ja nechcem jeho peniaze!', emotion: 'refusing' },
      { actor: 'Martin Horváth', text: 'Nie o peniaze ide. Ide o pravdu. O to, kto si.', emotion: 'sincere' },
    ],
    actors: ['Mária Kováčová', 'Martin Horváth'],
  },
  {
    title: 'Zuzana a Elena',
    titleSk: 'Zuzana a Elena',
    description: 'Zuzana visits Elena at the café. Best friends share a moment of honest conversation.',
    descriptionSk: 'Zuzana navštívi Elenu v kaviarni. Najlepšie priateľky zdieľajú úprimný rozhovor.',
    type: 'DIALOGUE',
    location: 'Interiér - Kaviareň',
    timeOfDay: 'Popoludnie',
    mood: 'intimate',
    duration: 90,
    order: 19,
    category: 'drama',
    dialogue: [
      { actor: 'Zuzana Bieliková', text: 'Ako dlho sa budeš tváriť, že je všetko v poriadku?', emotion: 'concerned' },
      { actor: 'Elena Kováčová', text: 'Kým nebude v poriadku.', emotion: 'stubborn' },
      { actor: 'Zuzana Bieliková', text: 'Elena. Som tvoja najlepšia priateľka. Vidím, že trpíš.', emotion: 'gentle' },
      { actor: 'Elena Kováčová', text: 'Babička zomrela. Mária sa vrátila. Tomáš chce odísť. Čo by som mala cítiť?', emotion: 'breaking' },
      { actor: 'Zuzana Bieliková', text: 'Tomáš chce odísť? To mi nepovedala!', emotion: 'shocked' },
      { actor: 'Elena Kováčová', text: 'Dostal ponuku v Bratislave. Dobrú ponuku.', emotion: 'sad' },
      { actor: 'Zuzana Bieliková', text: 'A ty? Pôjdeš s ním?', emotion: 'worried' },
      { actor: 'Elena Kováčová', text: 'Táto kaviareň je všetko, čo mám. Nemôžem ju opustiť.', emotion: 'conflicted' },
    ],
    actors: ['Elena Kováčová', 'Zuzana Bieliková'],
  },
  {
    title: 'Elena a pravda',
    titleSk: 'Elena a pravda',
    description: 'Maria tells Elena about their shared secret. The sisters finally begin to understand each other.',
    descriptionSk: 'Mária povie Elene o ich spoločnom tajomstve. Sestry sa konečne začínajú chápať.',
    type: 'EMOTIONAL',
    location: 'Interiér - Kaviareň, po zatváracej',
    timeOfDay: 'Noc',
    mood: 'emotional',
    duration: 150,
    order: 20,
    category: 'emotional',
    dialogue: [
      { actor: 'Mária Kováčová', text: 'Nie sme úplne sestry. Máme rôznych otcov.', emotion: 'sad' },
      { actor: 'Elena Kováčová', text: '(dlhá pauza) Čo tým myslíš?', emotion: 'confused' },
      { actor: 'Mária Kováčová', text: 'Mama mala vzťah s iným mužom. Rakúšanom. To on je môj biologický otec.', emotion: 'explaining' },
      { actor: 'Elena Kováčová', text: 'To... to nie je možné. Mama by nikdy...', emotion: 'denial' },
      { actor: 'Mária Kováčová', text: 'Babička to vedela. Celý čas. Preto mi nechala ten list.', emotion: 'revealing' },
      { actor: 'Elena Kováčová', text: '(dlhá pauza) Pre mňa si vždy bola a budeš moja sestra. Krv nie je všetko.', emotion: 'loving' },
      { actor: 'Mária Kováčová', text: '(plače) Prepáč mi. Za všetko ti prepáč.', emotion: 'emotional' },
      { actor: 'Elena Kováčová', text: 'Aj ty mne. Mali sme to vedieť skôr.', emotion: 'forgiving' },
    ],
    actors: ['Mária Kováčová', 'Elena Kováčová'],
  },
  {
    title: 'Jakubova ponuka',
    titleSk: 'Jakubova ponuka',
    description: 'Jakub finds Maria at the old spot in the vineyards. He opens his heart.',
    descriptionSk: 'Jakub nájde Máriu na starom mieste vo viniciach. Otvorí jej svoje srdce.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Vinice',
    timeOfDay: 'Západ slnka',
    mood: 'romantic',
    duration: 180,
    order: 21,
    category: 'romantic',
    dialogue: [
      { actor: 'Jakub Novák', text: 'Pamätáš si toto miesto?', emotion: 'nostalgic' },
      { actor: 'Mária Kováčová', text: 'Tu si ma prvýkrát pobozkal.', emotion: 'nostalgic' },
      { actor: 'Jakub Novák', text: 'Nikdy som na to nezabudol. Ani na teba. Zostaneš?', emotion: 'hopeful' },
      { actor: 'Mária Kováčová', text: 'Jakub... ja neviem, či viem byť tou Máriou, ktorú si miloval.', emotion: 'uncertain' },
      { actor: 'Jakub Novák', text: 'Nechcem tú Máriu. Chcem túto. Takú, aká si teraz.', emotion: 'sincere' },
      { actor: 'Mária Kováčová', text: 'Zmenila som sa. Nie som tá istá.', emotion: 'hesitant' },
      { actor: 'Jakub Novák', text: 'Všetci sme sa zmenili. To je život. Otázka je, či chceš byť súčasťou môjho.', emotion: 'open' },
    ],
    actors: ['Mária Kováčová', 'Jakub Novák'],
  },

  // ==========================================
  // AKT 4: ROZHODNUTIA (DECISIONS) - Scenes 22-28
  // ==========================================
  {
    title: 'Martinov odchod',
    titleSk: 'Martinov odchod',
    description: 'Martin decides to leave. He gives Maria a photo of their father.',
    descriptionSk: 'Martin sa rozhodne odísť. Dá Márii fotografiu ich otca.',
    type: 'DIALOGUE',
    location: 'Exteriér - Železničná stanica',
    timeOfDay: 'Ráno',
    mood: 'bittersweet',
    duration: 90,
    order: 22,
    category: 'drama',
    dialogue: [
      { actor: 'Martin Horváth', text: 'Neprišiel som sem zničiť váš svet. Len som chcel spoznať svoju sestru.', emotion: 'sincere' },
      { actor: 'Mária Kováčová', text: 'A spoznal si ju. Prídeš niekedy na návštevu?', emotion: 'warm' },
      { actor: 'Martin Horváth', text: 'Na Vianoce. Ak ma pozvete.', emotion: 'hopeful' },
      { actor: 'Mária Kováčová', text: 'Si vždy vítaný. Teraz už viem, že mám brata.', emotion: 'accepting' },
      { actor: 'Martin Horváth', text: 'Toto je jeho fotografia. Nášho otca. Chcel by, aby si ju mala.', emotion: 'giving' },
      { actor: 'Mária Kováčová', text: 'Ďakujem, Martin. Za všetko.', emotion: 'grateful' },
    ],
    actors: ['Mária Kováčová', 'Martin Horváth'],
  },
  {
    title: 'Tomášovo rozhodnutie',
    titleSk: 'Tomášovo rozhodnutie',
    description: 'Tomáš tells Elena he\'s turning down the job offer. He chooses her.',
    descriptionSk: 'Tomáš povie Elene, že odmietol pracovnú ponuku. Vybral si ju.',
    type: 'DIALOGUE',
    location: 'Interiér - Kaviareň',
    timeOfDay: 'Večer',
    mood: 'romantic',
    duration: 90,
    order: 23,
    category: 'romantic',
    dialogue: [
      { actor: 'Tomáš Kráľ', text: 'Odmietol som tú ponuku.', emotion: 'calm' },
      { actor: 'Elena Kováčová', text: 'Čo? Prečo? To bola tvoja príležitosť!', emotion: 'shocked' },
      { actor: 'Tomáš Kráľ', text: 'Moja príležitosť je tu. S tebou. V tomto meste.', emotion: 'sincere' },
      { actor: 'Elena Kováčová', text: 'Tomáš, nemôžeš kvôli mne obetovať svoju kariéru.', emotion: 'worried' },
      { actor: 'Tomáš Kráľ', text: 'Neobetujem nič. Získavam všetko, na čom mi záleží.', emotion: 'loving' },
      { actor: 'Elena Kováčová', text: '(plače) Si blázon. Úplný blázon.', emotion: 'happy-crying' },
      { actor: 'Tomáš Kráľ', text: 'Tvoj blázon. Ak ma ešte chceš.', emotion: 'playful' },
    ],
    actors: ['Elena Kováčová', 'Tomáš Kráľ'],
  },
  {
    title: 'Klavír',
    titleSk: 'Klavír',
    description: 'Maria finds her grandmother\'s old piano. She plays for the first time in years. Elena listens from the doorway.',
    descriptionSk: 'Mária nájde starý babičkin klavír. Prvýkrát po rokoch hrá. Elena počúva od dverí.',
    type: 'EMOTIONAL',
    location: 'Interiér - Obývačka',
    timeOfDay: 'Popoludnie',
    mood: 'nostalgic',
    duration: 120,
    order: 24,
    category: 'emotional',
    dialogue: [
      { actor: 'Elena Kováčová', text: '(šepká) Babička by bola šťastná, že znova hráš.', emotion: 'moved' },
      { actor: 'Mária Kováčová', text: 'Hrám pre ňu. A pre teba. A pre každého, koho som sklamala.', emotion: 'emotional' },
      { actor: 'Elena Kováčová', text: 'Nesklamala si ma. Len si mi chýbala.', emotion: 'honest' },
      { actor: 'Mária Kováčová', text: 'Ty si mi tiež chýbala. Viac, než si vieš predstaviť.', emotion: 'sincere' },
    ],
    actors: ['Mária Kováčová', 'Elena Kováčová'],
  },
  {
    title: 'Farárovo vyznanie',
    titleSk: 'Farárovo vyznanie',
    description: 'Father Peter visits Maria with final confession about her mother and his own regrets.',
    descriptionSk: 'Farár Peter navštívi Máriu s finálnym vyznaním o jej matke a vlastných výčitkách.',
    type: 'DIALOGUE',
    location: 'Interiér - Rodinný dom',
    timeOfDay: 'Večer',
    mood: 'somber',
    duration: 150,
    order: 25,
    category: 'drama',
    dialogue: [
      { actor: 'Peter Molnár', text: 'Miloval som tvoju matku. Celý život. Ale ona si vybrala iného.', emotion: 'regretful' },
      { actor: 'Mária Kováčová', text: 'Preto ste sa o nás vždy starali? Z lásky k nej?', emotion: 'understanding' },
      { actor: 'Peter Molnár', text: 'Z lásky k vám všetkým. Ste rodina, ktorú som nikdy nemal.', emotion: 'paternal' },
      { actor: 'Mária Kováčová', text: 'Vedeli ste o mojom skutočnom otcovi?', emotion: 'curious' },
      { actor: 'Peter Molnár', text: 'Vedel. Ale tvoj otec - ten, ktorý ťa vychoval - bol skutočný otec. V každom zmysle, na ktorom záleží.', emotion: 'wise' },
      { actor: 'Mária Kováčová', text: 'Prečo mi to nikto nepovedal skôr?', emotion: 'sad' },
      { actor: 'Peter Molnár', text: 'Pretože ťa milovali. A láska niekedy robí zbytočné tajomstvá.', emotion: 'philosophical' },
    ],
    actors: ['Mária Kováčová', 'Peter Molnár'],
  },
  {
    title: 'Spomienka - Rozchod',
    titleSk: 'Spomienka - Rozchod',
    description: 'Flashback: The moment young Maria told Jakub she was leaving. The pain of that day.',
    descriptionSk: 'Flashback: Moment, keď mladá Mária povedala Jakubovi, že odchádza. Bolesť toho dňa.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Vinice',
    timeOfDay: 'Západ slnka',
    mood: 'painful',
    duration: 90,
    order: 26,
    category: 'emotional',
    dialogue: [
      { actor: 'Mária Kováčová', text: '(mladá) Musím odísť. Dostala som štipendium vo Viedni.', emotion: 'conflicted' },
      { actor: 'Jakub Novák', text: '(mladý) Sľúbila si, že zostaneš. Že navždy...', emotion: 'heartbroken' },
      { actor: 'Mária Kováčová', text: '(mladá) Viem. Ale nemôžem tu zostať a celý život sa pýtať, čo by bolo, keby...', emotion: 'torn' },
      { actor: 'Jakub Novák', text: '(mladý) Takže to je všetko? Desať rokov spolu a ty len odídeš?', emotion: 'angry' },
      { actor: 'Mária Kováčová', text: '(mladá) Neodchádzam od teba. Idem za niečím. Je v tom rozdiel.', emotion: 'pleading' },
      { actor: 'Jakub Novák', text: '(mladý) Pre mňa nie je.', emotion: 'hurt' },
    ],
    actors: ['Mária Kováčová', 'Jakub Novák'],
  },
  {
    title: 'Rozhodnutie',
    titleSk: 'Rozhodnutie',
    description: 'Maria stands at the train station. She has a ticket to Vienna. Then she tears it up.',
    descriptionSk: 'Mária stojí na železničnej stanici. Má lístok do Viedne. Potom ho roztrhá.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Železničná stanica',
    timeOfDay: 'Ráno',
    mood: 'triumphant',
    duration: 60,
    order: 27,
    category: 'emotional',
    dialogue: [
      { actor: 'Mária Kováčová', text: '(k sebe) Desať rokov som behala. Od seba. Od nich. Od všetkého.', emotion: 'reflective' },
      { actor: 'Mária Kováčová', text: 'Nie. Tentoraz nie.', emotion: 'determined' },
      { actor: 'Mária Kováčová', text: 'Toto je môj domov. Vždy bol.', emotion: 'resolved' },
    ],
    actors: ['Mária Kováčová'],
  },
  {
    title: 'Telefonát agentovi',
    titleSk: 'Telefonát agentovi',
    description: 'Maria calls her agent in Vienna to cancel her upcoming concerts.',
    descriptionSk: 'Mária volá svojmu agentovi do Viedne, aby zrušila nadchádzajúce koncerty.',
    type: 'DIALOGUE',
    location: 'Exteriér - Námestie',
    timeOfDay: 'Ráno',
    mood: 'decisive',
    duration: 60,
    order: 28,
    category: 'drama',
    dialogue: [
      { actor: 'Mária Kováčová', text: 'Hans, musíme si pohovoriť.', emotion: 'serious' },
      { actor: 'Mária Kováčová', text: 'Viem, čo to znamená pre turné. Viem.', emotion: 'firm' },
      { actor: 'Mária Kováčová', text: 'Nie, neodchádzam z hudby. Len meníme plány.', emotion: 'reassuring' },
      { actor: 'Mária Kováčová', text: 'Koncert bude. Tu. Na Slovensku. V mojom domovskom meste.', emotion: 'excited' },
    ],
    actors: ['Mária Kováčová'],
  },

  // ==========================================
  // AKT 5: NOVÝ ZAČIATOK (NEW BEGINNING) - Scenes 29-35
  // ==========================================
  {
    title: 'Návrat do vinárstva',
    titleSk: 'Návrat do vinárstva',
    description: 'Maria returns to the winery. Jakub sees her coming. He runs to meet her.',
    descriptionSk: 'Mária sa vracia do vinárstva. Jakub ju vidí prichádzať. Beží jej v ústrety.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Vinice',
    timeOfDay: 'Ráno',
    mood: 'joyful',
    duration: 60,
    order: 29,
    category: 'romantic',
    dialogue: [
      { actor: 'Jakub Novák', text: 'Ty si sa vrátila!', emotion: 'ecstatic' },
      { actor: 'Mária Kováčová', text: 'Tentoraz navždy.', emotion: 'happy' },
      { actor: 'Jakub Novák', text: 'Navždy je dosť dlho.', emotion: 'playful' },
      { actor: 'Mária Kováčová', text: 'Nie dosť dlho pre nás.', emotion: 'loving' },
    ],
    actors: ['Mária Kováčová', 'Jakub Novák'],
  },
  {
    title: 'Príprava koncertu',
    titleSk: 'Príprava koncertu',
    description: 'The whole town helps prepare for Maria\'s concert at the café.',
    descriptionSk: 'Celé mesto pomáha pripraviť Máriin koncert v kaviarni.',
    type: 'DIALOGUE',
    location: 'Interiér - Kaviareň',
    timeOfDay: 'Popoludnie',
    mood: 'excited',
    duration: 90,
    order: 30,
    category: 'drama',
    dialogue: [
      { actor: 'Elena Kováčová', text: 'Svetlá idú sem! A kvety tam!', emotion: 'organizing' },
      { actor: 'Zuzana Bieliková', text: 'Kedy tu naposledy hrala slávna klaviristka?', emotion: 'excited' },
      { actor: 'Jakub Novák', text: 'Priniesol som víno. Najlepší ročník.', emotion: 'proud' },
      { actor: 'Peter Molnár', text: 'Tvoja babička by bola taká hrdá, Mária.', emotion: 'emotional' },
      { actor: 'Mária Kováčová', text: 'Vy všetci... ďakujem. Toto je ten najkrajší dar.', emotion: 'grateful' },
    ],
    actors: ['Mária Kováčová', 'Elena Kováčová', 'Jakub Novák', 'Zuzana Bieliková', 'Peter Molnár'],
  },
  {
    title: 'Otvorenie kaviarne',
    titleSk: 'Otvorenie kaviarne',
    description: 'Maria helps Elena with a special event at the café. The sisters work together.',
    descriptionSk: 'Mária pomáha Elene so špeciálnou udalosťou v kaviarni. Sestry pracujú spoločne.',
    type: 'DIALOGUE',
    location: 'Interiér - Kaviareň',
    timeOfDay: 'Popoludnie',
    mood: 'warm',
    duration: 90,
    order: 31,
    category: 'drama',
    dialogue: [
      { actor: 'Elena Kováčová', text: 'Vedela som, že máš umeleckú dušu, ale toto prekonalo moje očakávania.', emotion: 'impressed' },
      { actor: 'Mária Kováčová', text: 'Naučila ma to babička. Aj ty si od nej zdedila viac, než si myslíš.', emotion: 'warm' },
      { actor: 'Zuzana Bieliková', text: 'Vy dve ste konečne normálne? Tak to treba osláviť!', emotion: 'happy' },
      { actor: 'Elena Kováčová', text: 'Normálne? My sme nikdy neboli normálne!', emotion: 'laughing' },
      { actor: 'Mária Kováčová', text: 'A práve preto sme sestry.', emotion: 'loving' },
    ],
    actors: ['Mária Kováčová', 'Elena Kováčová', 'Zuzana Bieliková'],
  },
  {
    title: 'Babičkina pieseň',
    titleSk: 'Babičkina pieseň',
    description: 'Maria plays grandmother\'s favorite song on the piano at a gathering. The whole community is present.',
    descriptionSk: 'Mária hrá babičkinu obľúbenú pieseň na klavíri na spoločenskom stretnutí. Celá komunita je prítomná.',
    type: 'EMOTIONAL',
    location: 'Interiér - Kaviareň',
    timeOfDay: 'Večer',
    mood: 'bittersweet',
    duration: 180,
    order: 32,
    category: 'emotional',
    dialogue: [
      { actor: 'Mária Kováčová', text: 'Túto pieseň mi zahrala babička, keď som bola malá. Je pre ňu. A pre nás všetkých.', emotion: 'emotional' },
      { actor: 'Mária Kováčová', text: 'Babička vždy hovorila, že hudba je jazyk duše. Tak vám dnes hovorím svojou dušou.', emotion: 'heartfelt' },
      { actor: 'Peter Molnár', text: '(šepká) Úžasné. Úplne úžasné.', emotion: 'moved' },
      { actor: 'Elena Kováčová', text: '(plače potichu)', emotion: 'crying' },
    ],
    actors: ['Mária Kováčová', 'Elena Kováčová', 'Jakub Novák', 'Peter Molnár', 'Zuzana Bieliková', 'Tomáš Kráľ'],
  },
  {
    title: 'Po koncerte',
    titleSk: 'Po koncerte',
    description: 'After the concert, Maria and Jakub share a quiet moment outside.',
    descriptionSk: 'Po koncerte Mária a Jakub zdieľajú tichý moment vonku.',
    type: 'DIALOGUE',
    location: 'Exteriér - Pred kaviarňou',
    timeOfDay: 'Noc',
    mood: 'romantic',
    duration: 90,
    order: 33,
    category: 'romantic',
    dialogue: [
      { actor: 'Jakub Novák', text: 'Ten koncert bol neuveriteľný.', emotion: 'admiring' },
      { actor: 'Mária Kováčová', text: 'Hrala som pre teba. Uvedomuješ si to?', emotion: 'soft' },
      { actor: 'Jakub Novák', text: 'Pre mňa?', emotion: 'surprised' },
      { actor: 'Mária Kováčová', text: 'Pre teba. Za všetky tie roky, ktoré sme stratili.', emotion: 'sincere' },
      { actor: 'Jakub Novák', text: 'Nestratili sme ich. Len sme ich prežili oddelene.', emotion: 'philosophical' },
      { actor: 'Mária Kováčová', text: 'A teraz?', emotion: 'hopeful' },
      { actor: 'Jakub Novák', text: 'Teraz ich prežijeme spolu.', emotion: 'loving' },
    ],
    actors: ['Mária Kováčová', 'Jakub Novák'],
  },
  {
    title: 'Vinice pri západe slnka',
    titleSk: 'Vinice pri západe slnka',
    description: 'Maria and Jakub walk through the vineyards at sunset. He proposes. She says yes.',
    descriptionSk: 'Mária a Jakub sa prechádzajú vinicami pri západe slnka. On požiada o ruku. Ona povie áno.',
    type: 'EMOTIONAL',
    location: 'Exteriér - Vinice',
    timeOfDay: 'Západ slnka',
    mood: 'romantic',
    duration: 120,
    order: 34,
    category: 'romantic',
    dialogue: [
      { actor: 'Jakub Novák', text: 'Mária, zastavme sa tu.', emotion: 'nervous' },
      { actor: 'Mária Kováčová', text: 'Toto miesto... tu si ma prvýkrát...', emotion: 'remembering' },
      { actor: 'Jakub Novák', text: 'Pobozkal. A teraz ťa tu chcem požiadať o niečo iné.', emotion: 'serious' },
      { actor: 'Jakub Novák', text: 'Mária Kováčová. Vydáš sa za mňa?', emotion: 'loving' },
      { actor: 'Mária Kováčová', text: '(plače od šťastia) Áno. Tisíckrát áno.', emotion: 'overjoyed' },
      { actor: 'Jakub Novák', text: 'Čakal som na túto odpoveď desať rokov.', emotion: 'elated' },
      { actor: 'Mária Kováčová', text: 'Už nikdy nebudeš čakať. Sľubujem.', emotion: 'promising' },
    ],
    actors: ['Mária Kováčová', 'Jakub Novák'],
  },
  {
    title: 'Záverečné titulky',
    titleSk: 'Záverečné titulky',
    description: 'Final shot: Family photo from Maria and Jakub\'s wedding. Elena, Zuzana, Peter, even Martin are there. Fade to credits.',
    descriptionSk: 'Záverečný záber: Rodinná fotografia zo svadby Márie a Jakuba. Elena, Zuzana, Peter, dokonca aj Martin sú tam. Prechod do titulkov.',
    type: 'TRANSITION',
    location: 'Exteriér - Vinice',
    timeOfDay: 'Popoludnie',
    mood: 'joyful',
    duration: 90,
    order: 35,
    category: 'ending',
    dialogue: [
      { actor: 'Babička Anna', text: '(voice-over) Každá rodina má svoje tajomstvá. Ale láska ich všetky prekoná.', emotion: 'wise' },
      { actor: 'Babička Anna', text: '(voice-over) A niekedy sa musíme stratiť, aby sme sa našli.', emotion: 'poetic' },
      { actor: 'Babička Anna', text: '(voice-over) Toto je príbeh mojich vnučiek. Príbeh stratených sŕdc, ktoré sa našli.', emotion: 'loving' },
    ],
    actors: ['Mária Kováčová', 'Jakub Novák', 'Elena Kováčová', 'Zuzana Bieliková', 'Peter Molnár', 'Martin Horváth', 'Tomáš Kráľ'],
  },
]

// Scene categories for filtering
export const sceneCategories = [
  { id: 'drama', name: 'Drama', nameSk: 'Dráma', icon: 'Theater' },
  { id: 'romantic', name: 'Romantic', nameSk: 'Romantika', icon: 'Heart' },
  { id: 'emotional', name: 'Emotional', nameSk: 'Emotívne', icon: 'Smile' },
  { id: 'mystery', name: 'Mystery', nameSk: 'Záhada', icon: 'Search' },
  { id: 'opening', name: 'Opening', nameSk: 'Úvod', icon: 'Play' },
  { id: 'ending', name: 'Ending', nameSk: 'Záver', icon: 'Square' },
]

// Scene statistics for display
export const sceneStats = {
  totalScenes: 35,
  totalDialogueLines: demoScenes.reduce((acc, scene) => acc + (scene.dialogue?.length || 0), 0),
  byAct: {
    act1: { start: 1, end: 7, title: 'Návrat', titleEn: 'The Return' },
    act2: { start: 8, end: 14, title: 'Konfrontácie', titleEn: 'Confrontations' },
    act3: { start: 15, end: 21, title: 'Tajomstvá', titleEn: 'Secrets' },
    act4: { start: 22, end: 28, title: 'Rozhodnutia', titleEn: 'Decisions' },
    act5: { start: 29, end: 35, title: 'Nový začiatok', titleEn: 'New Beginning' },
  },
  byType: {
    ESTABLISHING: demoScenes.filter(s => s.type === 'ESTABLISHING').length,
    DIALOGUE: demoScenes.filter(s => s.type === 'DIALOGUE').length,
    EMOTIONAL: demoScenes.filter(s => s.type === 'EMOTIONAL').length,
    TRANSITION: demoScenes.filter(s => s.type === 'TRANSITION').length,
  },
  byCategory: {
    drama: demoScenes.filter(s => s.category === 'drama').length,
    romantic: demoScenes.filter(s => s.category === 'romantic').length,
    emotional: demoScenes.filter(s => s.category === 'emotional').length,
    mystery: demoScenes.filter(s => s.category === 'mystery').length,
    opening: demoScenes.filter(s => s.category === 'opening').length,
    ending: demoScenes.filter(s => s.category === 'ending').length,
  },
  totalDuration: demoScenes.reduce((acc, scene) => acc + scene.duration, 0),
}

// Generic preset scenes (not part of demo movie)
export const genericPresetScenes = [
  {
    title: 'Romantické stretnutie',
    titleSk: 'Romantické stretnutie',
    description: 'Two lovers meet after a long separation. Emotions run high.',
    descriptionSk: 'Dvaja milenci sa stretávajú po dlhom odlúčení. Emócie sú na maxime.',
    type: 'EMOTIONAL',
    category: 'romantic',
    tags: ['láska', 'stretnutie', 'emócie'],
  },
  {
    title: 'Dramatická konfrontácia',
    titleSk: 'Dramatická konfrontácia',
    description: 'Two characters confront each other about a betrayal.',
    descriptionSk: 'Dve postavy sa konfrontujú ohľadom zrady.',
    type: 'DIALOGUE',
    category: 'drama',
    tags: ['konflikt', 'zrada', 'napätie'],
  },
  {
    title: 'Tichý moment reflexie',
    titleSk: 'Tichý moment reflexie',
    description: 'A character alone, reflecting on their life choices.',
    descriptionSk: 'Postava osamote, premýšľa o svojich životných rozhodnutiach.',
    type: 'EMOTIONAL',
    category: 'emotional',
    tags: ['reflexia', 'samota', 'vnútorný monológ'],
  },
  {
    title: 'Rodinné tajomstvo',
    titleSk: 'Rodinné tajomstvo',
    description: 'A family secret is revealed, changing everything.',
    descriptionSk: 'Rodinné tajomstvo je odhalené a zmení všetko.',
    type: 'DIALOGUE',
    category: 'mystery',
    tags: ['tajomstvo', 'rodina', 'odhalenie'],
  },
  {
    title: 'Odpustenie',
    titleSk: 'Odpustenie',
    description: 'A moment of forgiveness between estranged family members.',
    descriptionSk: 'Moment odpustenia medzi odcudzenými členmi rodiny.',
    type: 'EMOTIONAL',
    category: 'emotional',
    tags: ['odpustenie', 'uzmierenie', 'rodina'],
  },
  {
    title: 'Žiadosť o ruku',
    titleSk: 'Žiadosť o ruku',
    description: 'A romantic marriage proposal scene.',
    descriptionSk: 'Romantická scéna so žiadosťou o ruku.',
    type: 'EMOTIONAL',
    category: 'romantic',
    tags: ['svadba', 'láska', 'romantika'],
  },
  {
    title: 'Posledná rozlúčka',
    titleSk: 'Posledná rozlúčka',
    description: 'Characters say goodbye, perhaps for the last time.',
    descriptionSk: 'Postavy sa lúčia, možno naposledy.',
    type: 'EMOTIONAL',
    category: 'drama',
    tags: ['rozlúčka', 'smútok', 'emócie'],
  },
  {
    title: 'Nečakané stretnutie',
    titleSk: 'Nečakané stretnutie',
    description: 'Two characters unexpectedly meet after years apart.',
    descriptionSk: 'Dve postavy sa nečakane stretnú po rokoch.',
    type: 'DIALOGUE',
    category: 'drama',
    tags: ['stretnutie', 'prekvapenie', 'minulosť'],
  },
  {
    title: 'Spoveď',
    titleSk: 'Spoveď',
    description: 'A character confesses a long-held secret.',
    descriptionSk: 'Postava sa prizná k dlho tajenému tajomstvu.',
    type: 'DIALOGUE',
    category: 'drama',
    tags: ['spoveď', 'tajomstvo', 'pravda'],
  },
  {
    title: 'Svadobný deň',
    titleSk: 'Svadobný deň',
    description: 'Wedding day celebration with family and friends.',
    descriptionSk: 'Oslava svadobného dňa s rodinou a priateľmi.',
    type: 'EMOTIONAL',
    category: 'romantic',
    tags: ['svadba', 'oslava', 'rodina'],
  },
]
