/**
 * Storyboard Visual Presets for FilmFlow AI
 * Cinematic visual prompts for AI image generation (Higgsfield compatible)
 * 50 storyboard frames for "Stratené Srdcia" (Lost Hearts)
 */

export const storyboardPresets = [
  // ==========================================
  // AKT 1: NÁVRAT (THE RETURN) - Frames 1-10
  // ==========================================
  {
    id: 'sb-001',
    sceneOrder: 1,
    category: 'establishing',
    name: 'Úvodný letecký záber',
    nameSk: 'Úvodný letecký záber',
    description: 'Opening aerial shot of Slovak countryside',
    prompt: 'Cinematic aerial establishing shot, picturesque Slovak village, autumn vineyard hills, church with white spire, morning mist in valleys, golden morning light, photorealistic, 4K quality, anamorphic lens flare',
    negativePrompt: 'modern buildings, urban, night, winter',
    resolution: '4K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'nostalgic',
    lighting: 'golden-hour',
    cameraMovement: 'drone_forward',
    tags: ['opening', 'aerial', 'establishing', 'countryside'],
  },
  {
    id: 'sb-002',
    sceneOrder: 2,
    category: 'establishing',
    name: 'Príchod vlaku na stanicu',
    nameSk: 'Príchod vlaku na stanicu',
    description: 'Train arriving at small Slovak station',
    prompt: 'Cinematic wide shot, vintage train arriving at small Slovak station, steam billowing, afternoon light streaming through station roof, photorealistic, nostalgic atmosphere, 35mm film aesthetic',
    negativePrompt: 'modern train, night, busy crowd, urban',
    resolution: '2K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'nostalgic',
    lighting: 'afternoon',
    cameraMovement: 'static',
    tags: ['train', 'station', 'arrival', 'establishing'],
  },
  {
    id: 'sb-003',
    sceneOrder: 2,
    category: 'portrait',
    name: 'Mária vystupuje z vlaku',
    nameSk: 'Mária vystupuje z vlaku',
    description: 'Maria stepping off the train',
    prompt: 'Cinematic medium shot, elegant Slovak woman age 32 stepping off vintage train, carrying small suitcase, looking around nostalgically, afternoon sunlight, photorealistic, shallow depth of field, 85mm lens',
    negativePrompt: 'crowd, modern clothing, night',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'melancholic',
    lighting: 'afternoon',
    cameraMovement: 'dolly_in',
    tags: ['portrait', 'maria', 'arrival', 'emotional'],
  },
  {
    id: 'sb-004',
    sceneOrder: 3,
    category: 'establishing',
    name: 'Námestie malého mesta',
    nameSk: 'Námestie malého mesta',
    description: 'Town square establishing shot',
    prompt: 'Cinematic wide establishing shot, charming Slovak town square, cobblestones, old buildings, afternoon shadows, locals walking, photorealistic, warm autumn colors, 35mm film grain',
    negativePrompt: 'modern cars, neon signs, night',
    resolution: '2K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'nostalgic',
    lighting: 'afternoon',
    cameraMovement: 'crane_down',
    tags: ['town', 'square', 'establishing', 'afternoon'],
  },
  {
    id: 'sb-005',
    sceneOrder: 4,
    category: 'dramatic',
    name: 'Prvý pohľad - Mária a Jakub',
    nameSk: 'Prvý pohľad - Mária a Jakub',
    description: 'First look between Maria and Jakub',
    prompt: 'Cinematic over-shoulder shot, Slovak woman spotting man loading wine crates across square, time frozen moment, shallow depth of field, golden afternoon light, emotional tension, photorealistic',
    negativePrompt: 'crowd between them, night, rain',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'tense',
    lighting: 'golden-hour',
    cameraMovement: 'slow_zoom',
    tags: ['romantic', 'first-look', 'tension', 'maria', 'jakub'],
  },
  {
    id: 'sb-006',
    sceneOrder: 4,
    category: 'portrait',
    name: 'Jakub detail - prekvapenie',
    nameSk: 'Jakub detail - prekvapenie',
    description: 'Close-up of Jakub recognizing Maria',
    prompt: 'Cinematic close-up, handsome Slovak man age 35, shocked recognition in eyes, wine crate in hands frozen, golden backlight, shallow depth of field, emotional moment, photorealistic, 85mm lens',
    negativePrompt: 'smiling, happy, crowd',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'portrait',
    mood: 'shocked',
    lighting: 'backlit',
    cameraMovement: 'static',
    tags: ['portrait', 'jakub', 'close-up', 'emotional'],
  },
  {
    id: 'sb-007',
    sceneOrder: 5,
    category: 'dramatic',
    name: 'Dvere rodinného domu',
    nameSk: 'Dvere rodinného domu',
    description: 'Elena opening door to family home',
    prompt: 'Cinematic medium shot, Slovak woman age 28 opening wooden door, cold expression, warm interior light behind her contrasting with cool exterior, dramatic lighting, photorealistic',
    negativePrompt: 'smiling, welcoming, bright',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'tense',
    lighting: 'contrast',
    cameraMovement: 'static',
    tags: ['elena', 'door', 'confrontation', 'home'],
  },
  {
    id: 'sb-008',
    sceneOrder: 5,
    category: 'dramatic',
    name: 'Konfrontácia sestier - vstupná hala',
    nameSk: 'Konfrontácia sestier - vstupná hala',
    description: 'Sisters confrontation in hallway',
    prompt: 'Cinematic two-shot, two Slovak women facing each other in dimly lit hallway, tension visible, warm tungsten from interior, dramatic shadows, photorealistic, 35mm film',
    negativePrompt: 'hugging, happy, bright lighting',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'tense',
    lighting: 'tungsten',
    cameraMovement: 'static',
    tags: ['sisters', 'confrontation', 'dramatic', 'interior'],
  },
  {
    id: 'sb-009',
    sceneOrder: 6,
    category: 'emotional',
    name: 'Babičkina izba',
    nameSk: 'Babičkina izba',
    description: 'Maria in grandmother\'s preserved room',
    prompt: 'Cinematic wide shot, Slovak woman standing alone in preserved elderly woman room, vintage furniture, photographs on walls, soft moonlight through lace curtains, melancholic atmosphere, photorealistic',
    negativePrompt: 'modern furniture, bright lights, daytime',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'sad',
    lighting: 'moonlight',
    cameraMovement: 'slow_push',
    tags: ['interior', 'grandmother', 'emotional', 'night'],
  },
  {
    id: 'sb-010',
    sceneOrder: 6,
    category: 'emotional',
    name: 'Mária s fotografiou',
    nameSk: 'Mária s fotografiou',
    description: 'Maria holding old photo, crying',
    prompt: 'Extreme close-up, Slovak woman hands holding old photograph of child with elderly woman, tears falling, soft lamplight, shallow depth of field, intimate emotional moment, photorealistic',
    negativePrompt: 'happy, smiling, bright',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'emotional',
    lighting: 'lamp-lit',
    cameraMovement: 'static',
    tags: ['close-up', 'photo', 'tears', 'emotional'],
  },

  // ==========================================
  // AKT 2: KONFRONTÁCIE - Frames 11-20
  // ==========================================
  {
    id: 'sb-011',
    sceneOrder: 8,
    category: 'establishing',
    name: 'Pohreb - celkový záber',
    nameSk: 'Pohreb - celkový záber',
    description: 'Funeral wide shot at cemetery',
    prompt: 'Cinematic wide shot, Slovak funeral at old cemetery, mourners in black gathered around grave, autumn leaves, overcast sky, church in background, fog in distance, photorealistic, somber atmosphere',
    negativePrompt: 'sunny, happy, vibrant colors',
    resolution: '4K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'somber',
    lighting: 'overcast',
    cameraMovement: 'crane',
    tags: ['funeral', 'cemetery', 'establishing', 'mourning'],
  },
  {
    id: 'sb-012',
    sceneOrder: 8,
    category: 'dramatic',
    name: 'Sestry na opačných stranách',
    nameSk: 'Sestry na opačných stranách',
    description: 'Sisters on opposite sides of grave',
    prompt: 'Cinematic medium shot, two women in black standing on opposite sides of open grave, other mourners between them, tension visible, overcast lighting, photorealistic, dramatic composition',
    negativePrompt: 'together, touching, sunny',
    resolution: '2K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'tense',
    lighting: 'overcast',
    cameraMovement: 'static',
    tags: ['funeral', 'sisters', 'separation', 'dramatic'],
  },
  {
    id: 'sb-013',
    sceneOrder: 9,
    category: 'romantic',
    name: 'Pri hrobe - Jakub prichádza',
    nameSk: 'Pri hrobe - Jakub prichádza',
    description: 'Jakub approaching Maria at graveside',
    prompt: 'Cinematic medium shot, Slovak woman alone at fresh grave, man approaching from behind, autumn cemetery, soft overcast light, leaves on ground, photorealistic, bittersweet atmosphere',
    negativePrompt: 'sunny, crowd, happy',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'bittersweet',
    lighting: 'overcast',
    cameraMovement: 'dolly_side',
    tags: ['cemetery', 'romantic', 'approach', 'emotional'],
  },
  {
    id: 'sb-014',
    sceneOrder: 10,
    category: 'establishing',
    name: 'Kaviareň interiér',
    nameSk: 'Kaviareň interiér',
    description: 'Café interior during wake',
    prompt: 'Cinematic wide interior shot, cozy Slovak café filled with mourners in black, vintage furniture, warm pendant lights, afternoon light through windows, photorealistic, somber yet warm atmosphere',
    negativePrompt: 'empty, modern, bright neon',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'somber',
    lighting: 'natural-mixed',
    cameraMovement: 'slow_pan',
    tags: ['café', 'interior', 'wake', 'establishing'],
  },
  {
    id: 'sb-015',
    sceneOrder: 10,
    category: 'portrait',
    name: 'Martin - tajomný cudzinec',
    nameSk: 'Martin - tajomný cudzinec',
    description: 'Martin mysterious stranger portrait',
    prompt: 'Cinematic medium shot, mysterious well-dressed Slovak man age 40, observing from corner of café, enigmatic expression, half in shadow, warm interior light, photorealistic, intriguing atmosphere',
    negativePrompt: 'smiling, in group, bright',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'portrait',
    mood: 'mysterious',
    lighting: 'chiaroscuro',
    cameraMovement: 'static',
    tags: ['portrait', 'martin', 'mysterious', 'stranger'],
  },
  {
    id: 'sb-016',
    sceneOrder: 12,
    category: 'dramatic',
    name: 'Nočná kuchyňa - konfrontácia',
    nameSk: 'Nočná kuchyňa - konfrontácia',
    description: 'Sisters confrontation in kitchen at night',
    prompt: 'Cinematic medium shot, two Slovak women facing each other in dimly lit kitchen, single overhead lamp, dramatic shadows, emotional tension, coffee cups on table, photorealistic, intense atmosphere',
    negativePrompt: 'bright, daylight, happy, outdoor',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'intense',
    lighting: 'single-source',
    cameraMovement: 'slow_orbit',
    tags: ['kitchen', 'night', 'confrontation', 'sisters'],
  },
  {
    id: 'sb-017',
    sceneOrder: 12,
    category: 'portrait',
    name: 'Elena - hnev a bolesť',
    nameSk: 'Elena - hnev a bolesť',
    description: 'Elena angry and hurt close-up',
    prompt: 'Cinematic close-up, Slovak woman age 28, angry tears in eyes, harsh overhead lighting casting shadows, emotional intensity, photorealistic, 85mm lens, shallow depth of field',
    negativePrompt: 'smiling, calm, bright',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'portrait',
    mood: 'angry',
    lighting: 'overhead',
    cameraMovement: 'static',
    tags: ['elena', 'close-up', 'angry', 'emotional'],
  },
  {
    id: 'sb-018',
    sceneOrder: 13,
    category: 'establishing',
    name: 'Vínna pivnica',
    nameSk: 'Vínna pivnica',
    description: 'Wine cellar interior',
    prompt: 'Cinematic wide interior, Slovak wine cellar, oak barrels in rows, candlelight and warm tungsten lamps, stone walls, atmospheric dust particles in light beams, photorealistic, rich atmosphere',
    negativePrompt: 'modern, fluorescent, sterile',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'atmospheric',
    lighting: 'candlelit',
    cameraMovement: 'dolly_through',
    tags: ['wine-cellar', 'interior', 'establishing', 'atmospheric'],
  },
  {
    id: 'sb-019',
    sceneOrder: 14,
    category: 'flashback',
    name: 'Flashback - prvý bozk',
    nameSk: 'Flashback - prvý bozk',
    description: 'Flashback first kiss in vineyard',
    prompt: 'Cinematic flashback scene, young Slovak couple about to kiss in vineyard, soft dreamy focus, golden hour backlight, slight lens flare, warm vintage color grading, photorealistic but ethereal, romantic atmosphere',
    negativePrompt: 'sharp focus, modern, cold colors, rain',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'flashback',
    mood: 'romantic',
    lighting: 'golden-dreamy',
    cameraMovement: 'slow_push',
    tags: ['flashback', 'romantic', 'vineyard', 'first-kiss'],
  },
  {
    id: 'sb-020',
    sceneOrder: 14,
    category: 'flashback',
    name: 'Flashback - mladý Jakub',
    nameSk: 'Flashback - mladý Jakub',
    description: 'Young Jakub making promise',
    prompt: 'Cinematic close-up flashback, young Slovak man age 22, looking lovingly at camera, vineyard bokeh background, golden hour light, soft dreamy quality, nostalgic color grading, photorealistic',
    negativePrompt: 'modern, harsh light, sad',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'flashback',
    mood: 'loving',
    lighting: 'golden-hour',
    cameraMovement: 'static',
    tags: ['flashback', 'jakub', 'young', 'romantic'],
  },

  // ==========================================
  // AKT 3: TAJOMSTVÁ (SECRETS) - Frames 21-30
  // ==========================================
  {
    id: 'sb-021',
    sceneOrder: 15,
    category: 'dramatic',
    name: 'Nájdený list',
    nameSk: 'Nájdený list',
    description: 'Maria finding hidden letter',
    prompt: 'Cinematic close-up, Slovak woman hands discovering old yellowed letter hidden in wooden box, dust particles in light beam, dramatic side lighting, photorealistic, mysterious atmosphere',
    negativePrompt: 'modern paper, bright, happy',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'mysterious',
    lighting: 'side-lit',
    cameraMovement: 'slow_zoom',
    tags: ['letter', 'discovery', 'mystery', 'close-up'],
  },
  {
    id: 'sb-022',
    sceneOrder: 15,
    category: 'emotional',
    name: 'Mária číta list - šok',
    nameSk: 'Mária číta list - šok',
    description: 'Maria reading letter, shocked',
    prompt: 'Extreme close-up, Slovak woman reading old letter, shock and confusion in eyes, dramatic side lighting, vintage paper visible, shallow depth of field, photorealistic, emotional intensity',
    negativePrompt: 'happy, smiling, bright',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'shocked',
    lighting: 'side-lit',
    cameraMovement: 'static',
    tags: ['maria', 'letter', 'shock', 'emotional'],
  },
  {
    id: 'sb-023',
    sceneOrder: 16,
    category: 'establishing',
    name: 'Povala - archív',
    nameSk: 'Povala - archív',
    description: 'Attic archive searching',
    prompt: 'Cinematic wide shot, Slovak woman searching through old boxes in dusty attic, shafts of light through small window, vintage photographs scattered, atmospheric dust, photorealistic',
    negativePrompt: 'modern storage, bright, clean',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'mysterious',
    lighting: 'shaft-light',
    cameraMovement: 'slow_pan',
    tags: ['attic', 'searching', 'mystery', 'photographs'],
  },
  {
    id: 'sb-024',
    sceneOrder: 17,
    category: 'dramatic',
    name: 'Kostol - konfrontácia s farárom',
    nameSk: 'Kostol - konfrontácia s farárom',
    description: 'Church confrontation with priest',
    prompt: 'Cinematic medium shot, Slovak woman confronting elderly priest in empty church, candlelight, dramatic shadows from stained glass, tense atmosphere, photorealistic, emotional intensity',
    negativePrompt: 'bright, crowded, happy',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'tense',
    lighting: 'candlelit',
    cameraMovement: 'slow_push',
    tags: ['church', 'confrontation', 'priest', 'dramatic'],
  },
  {
    id: 'sb-025',
    sceneOrder: 17,
    category: 'portrait',
    name: 'Farár Peter - výčitky',
    nameSk: 'Farár Peter - výčitky',
    description: 'Father Peter conflicted portrait',
    prompt: 'Cinematic close-up, elderly Slovak priest age 65, conflicted expression, candlelight on face, church interior background blur, photorealistic, emotional weight, 85mm lens',
    negativePrompt: 'smiling, bright, outdoor',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'portrait',
    mood: 'conflicted',
    lighting: 'candlelit',
    cameraMovement: 'static',
    tags: ['priest', 'portrait', 'conflicted', 'emotional'],
  },
  {
    id: 'sb-026',
    sceneOrder: 18,
    category: 'dramatic',
    name: 'Park - Martinovo odhalenie',
    nameSk: 'Park - Martinovo odhalenie',
    description: 'Park bench revelation scene',
    prompt: 'Cinematic two-shot, Slovak woman and mysterious man on park bench at twilight, city park background, dramatic blue hour lighting, tense body language, photorealistic, revelation atmosphere',
    negativePrompt: 'happy, laughing, bright day',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'shocking',
    lighting: 'blue-hour',
    cameraMovement: 'slow_orbit',
    tags: ['park', 'revelation', 'martin', 'dramatic'],
  },
  {
    id: 'sb-027',
    sceneOrder: 18,
    category: 'portrait',
    name: 'Mária - nevera v očiach',
    nameSk: 'Mária - nevera v očiach',
    description: 'Maria disbelief close-up',
    prompt: 'Cinematic extreme close-up, Slovak woman face showing disbelief and shock, tears forming, twilight blue light on skin, photorealistic, intense emotional moment, shallow depth of field',
    negativePrompt: 'calm, happy, bright',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'portrait',
    mood: 'disbelief',
    lighting: 'blue-hour',
    cameraMovement: 'static',
    tags: ['maria', 'close-up', 'shock', 'emotional'],
  },
  {
    id: 'sb-028',
    sceneOrder: 20,
    category: 'emotional',
    name: 'Sestry - objatie zmierenia',
    nameSk: 'Sestry - objatie zmierenia',
    description: 'Sisters reconciliation embrace',
    prompt: 'Cinematic medium shot, two Slovak women embracing emotionally in closed café, warm practical lighting, tears of reconciliation, intimate moment, photorealistic, cathartic atmosphere',
    negativePrompt: 'angry, fighting, cold light',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'emotional',
    lighting: 'warm-practical',
    cameraMovement: 'slow_push',
    tags: ['sisters', 'embrace', 'reconciliation', 'emotional'],
  },
  {
    id: 'sb-029',
    sceneOrder: 21,
    category: 'romantic',
    name: 'Vinice - Jakubova ponuka',
    nameSk: 'Vinice - Jakubova ponuka',
    description: 'Jakub opens heart in vineyard',
    prompt: 'Cinematic two-shot, Slovak couple in vineyard at golden hour, man speaking earnestly to woman, rolling hills background, warm sunset colors, lens flare, photorealistic, romantic atmosphere',
    negativePrompt: 'dark, rain, cold',
    resolution: '2K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'romantic',
    lighting: 'golden-hour',
    cameraMovement: 'slow_orbit',
    tags: ['vineyard', 'romantic', 'sunset', 'jakub', 'maria'],
  },
  {
    id: 'sb-030',
    sceneOrder: 21,
    category: 'romantic',
    name: 'Jakub a Mária - nádej',
    nameSk: 'Jakub a Mária - nádej',
    description: 'Maria and Jakub hopeful moment',
    prompt: 'Cinematic close two-shot, Slovak couple faces close together, golden sunset light on faces, hopeful expressions, shallow depth of field, vineyard bokeh, photorealistic, tender moment',
    negativePrompt: 'angry, cold, dark',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'hopeful',
    lighting: 'golden-hour',
    cameraMovement: 'static',
    tags: ['romantic', 'close-up', 'couple', 'hopeful'],
  },

  // ==========================================
  // AKT 4: ROZHODNUTIA - Frames 31-40
  // ==========================================
  {
    id: 'sb-031',
    sceneOrder: 22,
    category: 'emotional',
    name: 'Martinov odchod - stanica',
    nameSk: 'Martinov odchod - stanica',
    description: 'Martin departing at station',
    prompt: 'Cinematic medium shot, Slovak man and woman saying goodbye at train station, morning light, bittersweet expressions, train in background, photorealistic, emotional parting',
    negativePrompt: 'night, rain, angry',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'bittersweet',
    lighting: 'morning',
    cameraMovement: 'static',
    tags: ['station', 'goodbye', 'martin', 'emotional'],
  },
  {
    id: 'sb-032',
    sceneOrder: 22,
    category: 'portrait',
    name: 'Martin - fotografia otca',
    nameSk: 'Martin - fotografia otca',
    description: 'Martin giving photo to Maria',
    prompt: 'Cinematic close-up, man hands giving old photograph to woman hands, morning station light, emotional exchange, shallow depth of field, photorealistic, meaningful moment',
    negativePrompt: 'modern photo, digital, night',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'meaningful',
    lighting: 'morning',
    cameraMovement: 'static',
    tags: ['hands', 'photograph', 'exchange', 'emotional'],
  },
  {
    id: 'sb-033',
    sceneOrder: 23,
    category: 'romantic',
    name: 'Tomáš a Elena - rozhodnutie',
    nameSk: 'Tomáš a Elena - rozhodnutie',
    description: 'Tomáš choosing Elena',
    prompt: 'Cinematic medium shot, Slovak couple in café, man holding woman hands across table, warm evening light, emotional moment, vintage café interior, photorealistic, loving atmosphere',
    negativePrompt: 'arguing, cold, modern',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'romantic',
    lighting: 'warm-practical',
    cameraMovement: 'slow_push',
    tags: ['café', 'couple', 'romantic', 'decision'],
  },
  {
    id: 'sb-034',
    sceneOrder: 24,
    category: 'emotional',
    name: 'Mária pri klavíri',
    nameSk: 'Mária pri klavíri',
    description: 'Maria playing grandmother\'s piano',
    prompt: 'Cinematic wide shot, Slovak woman playing old upright piano in vintage living room, warm lamp light, afternoon sunlight through curtains, emotional expression, photorealistic, intimate atmosphere',
    negativePrompt: 'modern piano, concert hall, night',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'nostalgic',
    lighting: 'natural-mixed',
    cameraMovement: 'slow_dolly',
    tags: ['piano', 'music', 'emotional', 'interior'],
  },
  {
    id: 'sb-035',
    sceneOrder: 24,
    category: 'emotional',
    name: 'Elena počúva od dverí',
    nameSk: 'Elena počúva od dverí',
    description: 'Elena listening from doorway',
    prompt: 'Cinematic medium shot, Slovak woman standing in doorway listening, moved expression, soft backlight from room, silhouette partially visible, photorealistic, touching moment',
    negativePrompt: 'entering, speaking, bright',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'touched',
    lighting: 'backlit',
    cameraMovement: 'static',
    tags: ['doorway', 'listening', 'elena', 'emotional'],
  },
  {
    id: 'sb-036',
    sceneOrder: 26,
    category: 'flashback',
    name: 'Flashback - rozchod',
    nameSk: 'Flashback - rozchod',
    description: 'Flashback breakup scene',
    prompt: 'Cinematic flashback two-shot, young Slovak couple arguing in vineyard at sunset, painful expressions, dreamy soft focus, warm but sad color grading, photorealistic, heartbreaking atmosphere',
    negativePrompt: 'happy, modern, sharp focus',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'flashback',
    mood: 'painful',
    lighting: 'golden-hour',
    cameraMovement: 'slow_orbit',
    tags: ['flashback', 'breakup', 'vineyard', 'emotional'],
  },
  {
    id: 'sb-037',
    sceneOrder: 26,
    category: 'flashback',
    name: 'Mladá Mária - slzy',
    nameSk: 'Mladá Mária - slzy',
    description: 'Young Maria crying flashback',
    prompt: 'Cinematic close-up flashback, young Slovak woman age 22 crying, sunset light on tears, dreamy soft quality, vineyard background blur, nostalgic color grading, photorealistic',
    negativePrompt: 'happy, modern, sharp',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'flashback',
    mood: 'heartbroken',
    lighting: 'golden-hour',
    cameraMovement: 'static',
    tags: ['flashback', 'crying', 'maria', 'young'],
  },
  {
    id: 'sb-038',
    sceneOrder: 27,
    category: 'dramatic',
    name: 'Stanica - rozhodnutie',
    nameSk: 'Stanica - rozhodnutie',
    description: 'Maria tearing up ticket',
    prompt: 'Cinematic medium shot, Slovak woman at train station tearing up ticket, determined expression, morning light streaming through station, decisive moment, photorealistic, triumphant atmosphere',
    negativePrompt: 'sad, hesitant, night',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'triumphant',
    lighting: 'morning',
    cameraMovement: 'slow_zoom',
    tags: ['station', 'decision', 'ticket', 'triumphant'],
  },
  {
    id: 'sb-039',
    sceneOrder: 27,
    category: 'portrait',
    name: 'Mária - odhodlanie',
    nameSk: 'Mária - odhodlanie',
    description: 'Maria determined close-up',
    prompt: 'Cinematic close-up, Slovak woman face showing determination and resolve, morning light, slight smile forming, photorealistic, empowering moment, 85mm lens',
    negativePrompt: 'sad, crying, dark',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'portrait',
    mood: 'determined',
    lighting: 'morning',
    cameraMovement: 'static',
    tags: ['maria', 'portrait', 'determined', 'close-up'],
  },
  {
    id: 'sb-040',
    sceneOrder: 28,
    category: 'dramatic',
    name: 'Telefonát - nový plán',
    nameSk: 'Telefonát - nový plán',
    description: 'Maria calling agent',
    prompt: 'Cinematic medium shot, Slovak woman on phone in town square, excited expression, morning light, town backdrop, decisive conversation, photorealistic, hopeful atmosphere',
    negativePrompt: 'sad, indoor, night',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'excited',
    lighting: 'morning',
    cameraMovement: 'static',
    tags: ['phone', 'town', 'decision', 'hopeful'],
  },

  // ==========================================
  // AKT 5: NOVÝ ZAČIATOK - Frames 41-50
  // ==========================================
  {
    id: 'sb-041',
    sceneOrder: 29,
    category: 'romantic',
    name: 'Návrat do vinárstva',
    nameSk: 'Návrat do vinárstva',
    description: 'Maria returning to winery',
    prompt: 'Cinematic wide shot, Slovak woman walking through vineyard towards man in distance, morning golden light, beautiful landscape, joyful anticipation, photorealistic, romantic atmosphere',
    negativePrompt: 'rain, dark, sad',
    resolution: '4K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'joyful',
    lighting: 'golden-hour',
    cameraMovement: 'drone_follow',
    tags: ['vineyard', 'return', 'romantic', 'morning'],
  },
  {
    id: 'sb-042',
    sceneOrder: 29,
    category: 'romantic',
    name: 'Jakub beží v ústrety',
    nameSk: 'Jakub beží v ústrety',
    description: 'Jakub running to meet Maria',
    prompt: 'Cinematic tracking shot, Slovak man running through vineyard rows towards camera, joyful expression, golden morning light, motion blur background, photorealistic, ecstatic atmosphere',
    negativePrompt: 'walking, sad, dark',
    resolution: '2K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'ecstatic',
    lighting: 'golden-hour',
    cameraMovement: 'tracking_back',
    tags: ['running', 'jakub', 'vineyard', 'joyful'],
  },
  {
    id: 'sb-043',
    sceneOrder: 30,
    category: 'establishing',
    name: 'Príprava koncertu - kaviareň',
    nameSk: 'Príprava koncertu - kaviareň',
    description: 'Café being decorated for concert',
    prompt: 'Cinematic wide interior shot, Slovak café being decorated with lights and flowers, multiple people helping, afternoon light, festive preparation, photorealistic, warm community atmosphere',
    negativePrompt: 'empty, dark, formal',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'excited',
    lighting: 'afternoon',
    cameraMovement: 'slow_pan',
    tags: ['café', 'preparation', 'concert', 'community'],
  },
  {
    id: 'sb-044',
    sceneOrder: 32,
    category: 'emotional',
    name: 'Koncert - Mária hrá',
    nameSk: 'Koncert - Mária hrá',
    description: 'Maria performing at concert',
    prompt: 'Cinematic medium shot, Slovak woman playing piano at café concert, emotional expression, warm evening lighting, audience silhouettes, intimate performance, photorealistic, moving atmosphere',
    negativePrompt: 'large concert hall, bright stage lights, modern',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'emotional',
    lighting: 'warm-practical',
    cameraMovement: 'slow_orbit',
    tags: ['concert', 'piano', 'performance', 'emotional'],
  },
  {
    id: 'sb-045',
    sceneOrder: 32,
    category: 'emotional',
    name: 'Publikum - dojatá Elena',
    nameSk: 'Publikum - dojatá Elena',
    description: 'Elena crying in audience',
    prompt: 'Cinematic close-up, Slovak woman in audience crying tears of joy, warm concert lighting on face, shallow depth of field, other audience members blur, photorealistic, touching moment',
    negativePrompt: 'sad tears, angry, dark',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'touched',
    lighting: 'warm-practical',
    cameraMovement: 'static',
    tags: ['audience', 'elena', 'crying', 'emotional'],
  },
  {
    id: 'sb-046',
    sceneOrder: 33,
    category: 'romantic',
    name: 'Po koncerte - nočná ulica',
    nameSk: 'Po koncerte - nočná ulica',
    description: 'After concert quiet moment',
    prompt: 'Cinematic two-shot, Slovak couple standing outside café at night, warm light spilling from windows, intimate conversation, romantic atmosphere, photorealistic, quiet moment',
    negativePrompt: 'crowd, loud, bright',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'romantic',
    lighting: 'practical-night',
    cameraMovement: 'static',
    tags: ['night', 'couple', 'café', 'romantic'],
  },
  {
    id: 'sb-047',
    sceneOrder: 34,
    category: 'romantic',
    name: 'Západ slnka vo viniciach - finále',
    nameSk: 'Západ slnka vo viniciach - finále',
    description: 'Final vineyard sunset scene',
    prompt: 'Cinematic wide shot, Slovak couple walking through vineyard at golden sunset, rolling hills, romantic silhouettes, stunning landscape, lens flare, photorealistic, epic romantic atmosphere',
    negativePrompt: 'dark, rain, winter',
    resolution: '4K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'romantic',
    lighting: 'golden-hour',
    cameraMovement: 'crane_up',
    tags: ['vineyard', 'sunset', 'couple', 'romantic', 'finale'],
  },
  {
    id: 'sb-048',
    sceneOrder: 34,
    category: 'romantic',
    name: 'Žiadosť o ruku',
    nameSk: 'Žiadosť o ruku',
    description: 'Marriage proposal',
    prompt: 'Cinematic medium shot, Slovak man kneeling proposing to woman in vineyard, golden sunset, ring box visible, tears of joy, lens flare, photorealistic, peak romantic moment',
    negativePrompt: 'indoor, dark, sad',
    resolution: '2K',
    aspectRatio: '16:9',
    style: 'cinematic',
    mood: 'joyful',
    lighting: 'golden-hour',
    cameraMovement: 'slow_push',
    tags: ['proposal', 'romantic', 'vineyard', 'sunset'],
  },
  {
    id: 'sb-049',
    sceneOrder: 35,
    category: 'ending',
    name: 'Svadobná fotografia',
    nameSk: 'Svadobná fotografia',
    description: 'Wedding family photo',
    prompt: 'Cinematic wide shot, Slovak wedding group photo in vineyard, bride and groom with family and friends, afternoon golden light, joyful expressions, beautiful landscape backdrop, photorealistic',
    negativePrompt: 'indoor, formal, sad',
    resolution: '4K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'joyful',
    lighting: 'golden-hour',
    cameraMovement: 'static',
    tags: ['wedding', 'group', 'finale', 'joyful'],
  },
  {
    id: 'sb-050',
    sceneOrder: 35,
    category: 'ending',
    name: 'Záverečný záber - vinice',
    nameSk: 'Záverečný záber - vinice',
    description: 'Final shot vineyards fade to credits',
    prompt: 'Cinematic aerial shot pulling back from wedding party in vineyard, revealing stunning Slovak landscape, golden hour, fade to warm glow, epic finale shot, photorealistic, triumphant atmosphere',
    negativePrompt: 'dark, rain, close-up',
    resolution: '4K',
    aspectRatio: '2.39:1',
    style: 'cinematic',
    mood: 'triumphant',
    lighting: 'golden-hour',
    cameraMovement: 'drone_pullback',
    tags: ['aerial', 'finale', 'vineyard', 'credits'],
  },
]

// Storyboard statistics
export const storyboardStats = {
  total: storyboardPresets.length,
  byCategory: {
    establishing: storyboardPresets.filter(s => s.category === 'establishing').length,
    dramatic: storyboardPresets.filter(s => s.category === 'dramatic').length,
    romantic: storyboardPresets.filter(s => s.category === 'romantic').length,
    emotional: storyboardPresets.filter(s => s.category === 'emotional').length,
    portrait: storyboardPresets.filter(s => s.category === 'portrait').length,
    flashback: storyboardPresets.filter(s => s.category === 'flashback').length,
    ending: storyboardPresets.filter(s => s.category === 'ending').length,
  },
  byAct: {
    act1: storyboardPresets.filter(s => s.sceneOrder >= 1 && s.sceneOrder <= 7).length,
    act2: storyboardPresets.filter(s => s.sceneOrder >= 8 && s.sceneOrder <= 14).length,
    act3: storyboardPresets.filter(s => s.sceneOrder >= 15 && s.sceneOrder <= 21).length,
    act4: storyboardPresets.filter(s => s.sceneOrder >= 22 && s.sceneOrder <= 28).length,
    act5: storyboardPresets.filter(s => s.sceneOrder >= 29 && s.sceneOrder <= 35).length,
  },
}

// Storyboard style presets for quick selection
export const stylePresets = {
  cinematic: {
    name: 'Filmový štýl',
    nameSk: 'Filmový štýl',
    prompt_prefix: 'Cinematic shot, photorealistic, 35mm film grain, shallow depth of field, ',
    color_grading: 'cinematic color grading',
    aspect_ratio: '2.39:1',
  },
  portrait: {
    name: 'Portrétový štýl',
    nameSk: 'Portrétový štýl',
    prompt_prefix: 'Portrait photography, 85mm lens, shallow depth of field, studio quality, ',
    color_grading: 'natural skin tones',
    aspect_ratio: '4:3',
  },
  vintage: {
    name: 'Vintage štýl',
    nameSk: 'Vintage štýl',
    prompt_prefix: 'Vintage film photography, nostalgic atmosphere, warm color palette, slight grain, ',
    color_grading: 'faded vintage tones',
    aspect_ratio: '4:3',
  },
  dramatic: {
    name: 'Dramatický štýl',
    nameSk: 'Dramatický štýl',
    prompt_prefix: 'Dramatic lighting, high contrast, moody atmosphere, cinematic shadows, ',
    color_grading: 'high contrast dramatic',
    aspect_ratio: '16:9',
  },
  romantic: {
    name: 'Romantický štýl',
    nameSk: 'Romantický štýl',
    prompt_prefix: 'Romantic soft lighting, golden hour, dreamy atmosphere, warm tones, ',
    color_grading: 'warm romantic tones',
    aspect_ratio: '16:9',
  },
  flashback: {
    name: 'Flashback štýl',
    nameSk: 'Flashback štýl',
    prompt_prefix: 'Dreamy flashback scene, soft focus, nostalgic color grading, ethereal lighting, ',
    color_grading: 'warm nostalgic tones',
    aspect_ratio: '16:9',
  },
}

// Lighting presets
export const lightingPresets = [
  { id: 'golden-hour', name: 'Zlatá hodina', nameSk: 'Zlatá hodina', description: 'Warm sunset/sunrise light' },
  { id: 'blue-hour', name: 'Modrá hodina', nameSk: 'Modrá hodina', description: 'Cool twilight ambiance' },
  { id: 'overcast', name: 'Zamračené', nameSk: 'Zamračené', description: 'Soft diffused daylight' },
  { id: 'tungsten', name: 'Žiarovkové', nameSk: 'Žiarovkové', description: 'Warm artificial indoor' },
  { id: 'candlelit', name: 'Sviečky', nameSk: 'Sviečky', description: 'Romantic flickering light' },
  { id: 'moonlight', name: 'Mesačné', nameSk: 'Mesačné', description: 'Cool silvery night' },
  { id: 'rembrandt', name: 'Rembrandt', nameSk: 'Rembrandt', description: 'Dramatic portrait lighting' },
  { id: 'backlit', name: 'Protisvietlo', nameSk: 'Protisvietlo', description: 'Silhouette/rim lighting' },
  { id: 'window', name: 'Od okna', nameSk: 'Od okna', description: 'Natural window light' },
  { id: 'practical', name: 'Praktické', nameSk: 'Praktické', description: 'On-set practical lights' },
  { id: 'chiaroscuro', name: 'Chiaroscuro', nameSk: 'Chiaroscuro', description: 'Strong light/shadow contrast' },
  { id: 'morning', name: 'Ranné', nameSk: 'Ranné', description: 'Fresh morning daylight' },
]

// Note: cameraMovements is exported from ./camera-movements.ts

// Camera angles/shots
export const cameraPresets = [
  { id: 'wide', name: 'Celkový záber', nameSk: 'Celkový záber', prompt: 'wide establishing shot' },
  { id: 'medium', name: 'Polocelok', nameSk: 'Polocelok', prompt: 'medium shot' },
  { id: 'close-up', name: 'Detail', nameSk: 'Detail', prompt: 'close-up shot' },
  { id: 'extreme-close-up', name: 'Extrémny detail', nameSk: 'Extrémny detail', prompt: 'extreme close-up' },
  { id: 'over-shoulder', name: 'Cez plece', nameSk: 'Cez plece', prompt: 'over the shoulder shot' },
  { id: 'two-shot', name: 'Dvojzáber', nameSk: 'Dvojzáber', prompt: 'two shot with both subjects' },
  { id: 'low-angle', name: 'Podhľad', nameSk: 'Podhľad', prompt: 'low angle shot' },
  { id: 'high-angle', name: 'Nadhľad', nameSk: 'Nadhľad', prompt: 'high angle shot looking down' },
  { id: 'dutch', name: 'Holandský uhol', nameSk: 'Holandský uhol', prompt: 'dutch angle tilted' },
  { id: 'aerial', name: 'Letecký', nameSk: 'Letecký', prompt: 'aerial drone shot' },
  { id: 'pov', name: 'POV', nameSk: 'POV', prompt: 'point of view shot' },
  { id: 'tracking', name: 'Tracking', nameSk: 'Tracking', prompt: 'tracking shot following subject' },
]
